### ISSUE TITLE
Saving data in closed Obsidian

### ISSUE THREAD

**Issue by AlexGorEc** [obsidianmd/obsidian-clipper#101]
Good afternoon!
I don't understand programming very well. But I really like Obsidian and everything related to it.
My storage is in the cloud on google disk.
Suppose my Obsidian vault is not open. How can I save a page from my browser to my vault if:
1. I am browsing something on my computer (Windows 10/11)?
2. I'm browsing on my phone (Android)?
3. I'm browsing on a tablet (iPad)?

**Comment by kepano** [comment]
Please use the Discord channel for help and discussion about Web Clipper. Issues should be reserved for bugs and feature requests.
https://discord.com/channels/686053708261228577/1285652864089198672
