### ISSUE TITLE
Add new parameters to automatically identify and retrieve specific content from certain websites.

### ISSUE THREAD

**Issue by tyf2018** [obsidianmd/obsidian-clipper#103]
Preset variables {{content}} cannot identify and retrieve specific content from certain websites, such as the attachment links on https://stic.sz.gov.cn/xxgk/tzgg/content/post_11566869.html (as shown in the following screenshot). I expect it to automatically identify and save this content instead of requiring manual selection each time.

![image](https://github.com/user-attachments/assets/782a6c6a-0674-4ce0-9c58-efc33104d0ca)

Best regards.

**Comment by kepano** [comment]
Please read the documentation. That's what selector variables are for.
