### ISSUE TITLE
BUG: loss part of the page

### ISSUE THREAD

**Issue by Kurt-Shiwz** [obsidianmd/obsidian-clipper#106]
**Version (please complete the following information):**
 - OS: [macos m1]
 - Browser [edge]
 - Web Clipper version: [0.9.4]
- Obsidian version: [130.0.2849.56]

**Describe the bug**
loss part of the page.
for example:https://www.feishu.cn/hc/zh-CN/articles/803525191890-%E4%BA%91%E6%96%87%E6%A1%A3%E4%BB%8B%E7%BB%8D
in page:
![image](https://github.com/user-attachments/assets/e4da07b2-ccbc-4263-80aa-d7dae75e858f)

download, `loss section`:
![image](https://github.com/user-attachments/assets/694c598a-bab5-493d-b15c-8d99b703efd9)

**Your template file**
[obsidian-web-clipper-settings.json](https://github.com/user-attachments/files/17539796/obsidian-web-clipper-settings.json)

**Comment by kepano** [comment]
Same issue as #117
