### ISSUE TITLE
BUG: abnormal highlighting behavior in Wikipedia pages

### ISSUE THREAD

**Issue by sylph520** [obsidianmd/obsidian-clipper#107]
**Version (please complete the following information):**
 - OS: Windows
 - Browser  Firefox ESR 128.3.1
 - Web Clipper version: 0.9.4
- Obsidian version: 1.7.4

**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
The case is that I only want to select one sentence of a paragraph in a Wikipedia entry, but the clipper extension highlighted an area

**To reproduce**
1. Go to a Wikipedia page, e.g., https://en.wikipedia.org/wiki/Ridge_regression
2. open the highlighter of the clipper to select the first sentence "Ridge regression is a method of estimating the coefficients of multiple-regression models in scenarios where the independent variables are highly correlated." or select the sentence then use contex menu to add to highlight.
3. a whole area was highlighted
![image](https://github.com/user-attachments/assets/c18ac38a-b0cf-49ae-8b95-15417fb420b1)

**Expected behavior**
only the selected sentence will be highlighted. 

**Your template file**
The default template file.

**Comment by lucashabersaat** [comment]
Came across the same issue. 

I think the problem is, that when the highlighted area includes the first character of a paragraph (even though it ends before the end of the paragraph), the whole paragraph is highlighted.

- Excluding the first character will work fine
- Doesn't matter if the highlighting start or ends with the first character

https://github.com/user-attachments/assets/1e8ce442-0b34-4348-9636-36968ff21f4f

**Comment by juandarr** [comment]
Yes, I am experiencing the same bug. I want to highlight a subset of a paragraph which includes its first word, so the expected result is to highlight just the subset. The tool highlights the whole paragraph instead, which is not the desired action.

**Comment by sylph520** [comment]
> Came across the same issue.
> 
> I think the problem is, that when the highlighted area includes the first character of a paragraph (even though it ends before the end of the paragraph), the whole paragraph is highlighted.
> 
>     * Excluding the first character will work fine
> 
>     * Doesn't matter if the highlighting start or ends with the first character
> 
> 
> Screen.Recording.2024-11-13.at.11.56.22.mov

👍 Yes, excluding the first character will work, although it is not the intended behavior. Hope this useful information can help the developer identify the bug and fix it.
