### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by odevroed** [obsidianmd/obsidian-clipper#108]
**Version (please complete the following information):**
 - OS: [Fedora 40]
 - Browser [Chrome and Firefox]
 - Web Clipper version: [?]
- Obsidian version: [1.7.4]

**Describe the bug**
When I clip a page, a new note is created in Obsidian with the correct title but without the page's content. 
The properties are not added either. 
In essence, I get an empty note with a title.
I tried chrome and firefox. I also tried {{content}} and {{contentHtml}}

All tests were done with a fresh install of Web Clipper and the (unchanged) default template.

**Comment by kepano** [comment]
Did you register the URI?
https://help.obsidian.md/Extending+Obsidian/Obsidian+URI#Register+Obsidian+URI

If yes, what do you see in the developer console in Obsidian?

**Comment by odevroed** [comment]
Thanks for your prompt answer.

I indeed misses that instruction in the github page (but could not find this on the official page on the obsidian site though).

In any case: I made the file and it works now for Firefox. However, Chrome still only gives the title. I opened the console (ctrl+shit+i) but as I have no idea what I'm looking for, I don't know what to report. I can help you debug if you want to.

**Comment by cliotusna** [comment]
I also have this bug, OS Kubuntu 24.04 with Firefox and the Obsidian 1.7.4 (deb package).

With legacy mode off the bug occurs, and the developer console says:
"Web Clipper requires Obsidian 1.7.2 or above. You may need to install the early access version, or enable legacy mode in Web Clipper settings."

Which shows up in the note body if I use {contentHtml} in the template.

Enabling legacy mode fills the missing fields.

**Comment by kepano** [comment]
Please review Linux troubleshooting steps here:
https://help.obsidian.md/Extending+Obsidian/Obsidian+Web+Clipper#Linux
