### ISSUE TITLE
while simple to make, include a "bookmark" clipper

### ISSUE THREAD

**Issue by pcause** [obsidianmd/obsidian-clipper#110]
While simple to make the template, not every user will know how or think of how to create a template to clip the URL of a page they are viewing and save to read it later.  I think you should include in the base install a Book,ark template.  The template save the URL with page title to the end of a note.  The Note defaults to /Bookmarks or perhaps a bookmarks.md note in the default clipper folder.  Each bookmark would have [title](url) and the metadata as a callout below that, collapsed.  perhaps an option to be collapsed or not.

As always, user's can edit to place this at a different location, specify which metadata is saved, bottom or top of page and the like.

If possible allow a metadata field to specify a heading the bookmark is saved under.  If a header is specified that bottom/top of page mean top or bottom of items under that header

EDIT:  Perhaps a new behaviors would be top/bottom of bookmarks page

**Comment by kepano** [comment]
I am not sure I understand what you are saying. Do you mean that Web Clipper should support saving a page to the Obsidian Bookmarks plugin as opposed to saving it as a note?

If you mean saving the bookmark as a regular note, then this is already possibly by duplicating and/or modifying the default template. In the future we'll add more ways to explore and download community templates.
