### ISSUE TITLE
BUG: inconsistent prompt behavior (JSON vs. raw response)

### ISSUE THREAD

**Issue by laughedelic** [obsidianmd/obsidian-clipper#114]
I know the interpreter is not an officially released feature, but I thought I'd report this observed _unexpected_ behavior (not sure if it's necessarily a bug), in case you'd want to change it before the release. I can also contribute a fix (if you accept pull-requests).

---

**Version (please complete the following information):**

- OS: macOS 14.6.1
- Browser: Arc
- Web Clipper version: 0.9.4
- Obsidian version: 1.7.4 (Installer 1.6.7)

**Describe the bug**

`{{prompt}}` sometimes returns a markdown that can be inlined directly, and sometimes a JSON. I think this inconsistent behavior is unintended.

**To reproduce**

Use this template (full JSON below):

```
{{prompt:"a markdown bullet-point list of the main takeaways with sub-points for the important details"}}
```

I tried a few different ways to prompt for a "list", a "nested list", a "bullet-point markdown list", etc. but every time it would return a JSON array or JSON object. So I landed on asking for an array and using `|list` filter to convert it to a markdown list.

For example for the [Obsidian Web Clipper](https://help.obsidian.md/Extending+Obsidian/Obsidian+Web+Clipper) page it returns:

<details><summary>Lengthy output</summary>

```
[
  "Obsidian Web Clipper Overview",
  "- A browser extension for saving web content to your Obsidian vault.",
  "Getting Started",
  "- Install from browser-specific directories: Chrome, Firefox, or Safari.",
  "- Requires Obsidian version 1.7.2 or above.",
  "Basic Usage",
  "- Access Web Clipper through browser icon, hotkeys, or context menu.",
  "- Use 'Add to Obsidian' to save content.",
  "Interface Structure",
  "- Header: Switch templates, enable highlighter, access settings.",
  "- Properties: Metadata extracted from the page.",
  "- Note Content: Content to be saved to Obsidian.",
  "- Footer: Select vault and folder.",
  "Templates",
  "- Create templates to capture and organize page metadata.",
  "- Import and export templates using JSON files.",
  "Template Triggers",
  "- Automatically select templates based on URL or schema.org data.",
  "Variables in Templates",
  "- Use preset, meta, selector, and schema variables to populate data.",
  "Filters",
  "- Modify variables with various filters for dates, text, arrays, etc.",
  "HTML Processing",
  "- Tools for handling HTML to Markdown conversion."
]
```

</details>

I also tried instructing it explicitly to not use JSON:

```
{{prompt:"a markdown bullet-point list of the main takeaways with sub-points for the important details. format it as a single Markdown string, not a JSON array"}}
```

and that returned an empty response.

I tested it mostly with **gpt4o-mini**.

**Expected behavior**

I expect it to always return markdown (or a "raw" response), unless instructed otherwise. 

Or maybe always return JSON with some predictable structure (although I think it's much less user-friendly). I can appreciate structured output that can be processed with filters, but I think the current behavior is inconsistent and confusing.

**Your template file**

```json
{
	"schemaVersion": "0.1.0",
	"name": "Summarize bug report",
	"behavior": "create",
	"noteContentFormat": "{{prompt:\"a markdown bullet-point list of the main takeaways with sub-points for the important details\"}}",
	"properties": [],
	"triggers": [],
	"noteNameFormat": "{{title}}",
	"path": "clippings"
}
```

---

I've identified these relevant locations in the code:

- System prompt *instructs* the model to return JSON:
  
  https://github.com/obsidianmd/obsidian-clipper/blob/bea800d5894876e6ef2bc0a9c57d4b443dc5e66a/src/utils/interpreter.ts#L24
  
- The reponse is either parsed as JSON or returned *raw*:
  
  https://github.com/obsidianmd/obsidian-clipper/blob/bea800d5894876e6ef2bc0a9c57d4b443dc5e66a/src/utils/interpreter.ts#L122-L131
  
- There is some special handling of the array an object responses:
  
  https://github.com/obsidianmd/obsidian-clipper/blob/bea800d5894876e6ef2bc0a9c57d4b443dc5e66a/src/utils/interpreter.ts#L433-L441
  
  I'm not sure what the intent was here, but I suspect that this is the place causing the behavior described above.

**Comment by kepano** [comment]
The feature is not completed and not yet documented.
