### ISSUE TITLE
About author and published values not working

### ISSUE THREAD

**Issue by sa-nny** [obsidianmd/obsidian-clipper#116]
Why are the author and published values not working when clipping Bilibili web pages, but they work for YouTube? I have tried several values without success:

author: This value should return the author's name.

Inputting {{author|split:", "|wikilink|join}} returns a URL.
Inputting {{meta.author|wikilink}} returns empty.
Inputting {{schema:author|wikilink}} returns empty, but it works for YouTube.
published: This value should return the video upload date rather than the update or access date.

Inputting {{published}} returns a URL.
Inputting {{date|date:YYYY-MM-DD}} returns the latest date, not the upload date.
Inputting {{schema:uploadDate|date:YYYY-MM-DDTHH:mm:ss}} returns the latest date, not the upload date, but it works for YouTube.
Inputting {{meta.uploadDate|date:YYYY-MM-DD}} returns empty.
Other attributes such as title, source, created, and tags work fine.

Browser version used: Chrome 130.0.6723.91 (Official Build) (64-bit)

**Comment by kepano** [comment]
Every website has different formatting so it is almost impossible to capture them all accurately. You can use a custom YouTube template like the one in the clipper templates repo.

**Comment by sa-nny** [comment]
Can someone help me with this? Using {{date}} works, but it's not the result I want. What value should I use to get the Bilibili video upload time? Additionally, what value should I use for the author?

**Comment by kepano** [comment]
Please use the Discord channel for help with templates. You can also access the YouTube template in the clipper templates repo. See readme.
