### ISSUE TITLE
BUG: Substack paragraph titles not exported

### ISSUE THREAD

**Issue by exmateriae** [obsidianmd/obsidian-clipper#117]
**Version (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Web Clipper version: [e.g. 0.9.4]
- Obsidian version: [e.g. 1.7.4]

**Describe the bug**
When clipping a complete article from Substack, if there are titles through it, they are not exported by the clipper, as if it does not see them. To my knowledge the paragraph titles from Substack are headers level 4 : ####

For the exact same text, this error does not happen on other sites. For instance, the same content on Substack and Lesswrong:
https://thezvi.substack.com/p/ai-88-thanks-for-the-memos
https://www.lesswrong.com/posts/HHkYEyFaigRpczhHy/ai-88-thanks-for-the-memos#comments

**Expected behavior**
Having the paragraph titles in the export.

**Comment by kepano** [comment]
The issue is present in Readability.js so you'll need to create a site template for now instead of using {{content}}

**Comment by exmateriae** [comment]
Thank you I'm going to try this!

**Comment by kepano** [comment]
Refer to this issue:
https://github.com/mozilla/readability/issues/821

**Comment by fpehar** [comment]
this works form me and captures headings along with the content
`
# {{title}}

{{select: h1, h2, h3, h4, h5, h6}}

{{content}}
`

**Comment by mpfilbin** [comment]
> this works form me and captures headings along with the content
> 
> ```
> # {{title}}
> 
> {{select: h1, h2, h3, h4, h5, h6}}
> 
> {{content}}
> ```

I tried this without much success; however, this did work for me:

```
{{selectorHtml:div.body.markup|markdown}}
```

While I haven't tested it extensively, it seems reliable for many Substacks.
