### ISSUE TITLE
BUG: The code segment in the WeChat public account article is formatted incorrectly

### ISSUE THREAD

**Issue by zen010101** [obsidianmd/obsidian-clipper#118]
see here: [函数式编程和设计模式](https://mp.weixin.qq.com/s?__biz=MzkxNzE4MDM0Mw%3D%3D&chksm=c145d840f63251563b2548ad2218a66f184ca1f256f601d38dad8a62f1f9759133140f4589c1&cur_album_id=2476583222705897474&idx=1&mid=2247484056&scene=178&sn=ee7cb45c101967261c42bfc01838a62d)

**Comment by PackRuble** [comment]
Similarly, although somehow previously it was possible to save the formatting

ex: https://habr.com/ru/articles/814411/

**Comment by kepano** [comment]
Closing in favor of #145
