### ISSUE TITLE
Feature: fetch HTML keywords as keywords when available.

### ISSUE THREAD

**Issue by tbrittoborges** [obsidianmd/obsidian-clipper#123]
There should be configurable support for extracting keywords from the links, such as HTML keywods meta, that are exported as obsidian tags.

**Comment by kepano** [comment]
This is already possible using meta variables {{meta:name:keywords}}

https://help.obsidian.md/Extending+Obsidian/Obsidian+Web+Clipper#Meta+variables

**Comment by tbrittoborges** [comment]
Thanks for the info, I will try it and report back.
