### ISSUE TITLE
BUG: missing code blocks 

### ISSUE THREAD

**Issue by Jopp-gh** [obsidianmd/obsidian-clipper#131]
**Version (please complete the following information):**
 - OS: Linux Mint
 - Web Clipper version: 0.9.4
 - Obsidian version: 1.7.4

**Describe the bug**
I downloaded Obsidian Web Clipper from: https://chromewebstore.google.com/detail/obsidian-web-clipper/cnjifjpddelmedmihgijeibhnjfabmlf
`Obsidian Web Clipper` ignores code blocks/code fences, like :

```bash
#some commands
```

**To reproduce**
1. Download the main ReadMe from https://github.com/obsidianmd/obsidian-clipper with Obsidian Web Clipper
2. check your new import in Obsidian and you'll see code blocks are missing, eg, if you check under `To build the extension:` there's nothing. 

**Expected behavior**
export code fences/code blocks too

**Comment by kepano** [comment]
It seems that the issue is upstream in Readability:
https://github.com/mozilla/readability/issues/374

Please follow the troubleshooting steps here:
https://help.obsidian.md/web-clipper/troubleshoot#Some+content+is+missing
