### ISSUE TITLE
BUG: "Add to Obsidian" does nothing on Linux Firefox

### ISSUE THREAD

**Issue by danlamanna** [obsidianmd/obsidian-clipper#132]
**Version**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Web Clipper version: 0.9.4
- Obsidian version: 1.7.5

**Describe the bug**
When clicking "Add to Obsidian", the Firefox web console is cleared and then nothing happens. Notably Obsidian never logs the `Received URL action` in its console.

**To reproduce**
1. Go to any URL
2. Click on the web clipper
3. Click "Add to Obsidian"
4. Observe that the article wasn't added to Obsidian

**Expected behavior**
The article to be added to Obsidian.

**Your template file**
I'm using the "Default" template.

**Other things I've noticed**
- I've tested this in Brave (chromium-based) and it works correctly, which maybe eliminates my `.desktop` file being incorrect. (`xdg-open 'obsidian://open?vault=main` works on the command line as well).
- There are no errors of note in the Firefox web console or the Obsidian console.
- I'm **not** running Firefox as a snap.
- I'm using the Obsidian AppImage and the error occurs whether or not I point my `.desktop` file to the extracted squashfs binary.
- I've tried using legacy mode, the error occurs with and without it.
- I've disabled all other extensions in Firefox and the problem persists.

I assume this is some form of Firefox being Firefox, but I'm totally out of ideas. Thanks for taking a look :)

**Comment by kepano** [comment]
Did you try the troubleshooting steps?

https://help.obsidian.md/web-clipper/troubleshoot

**Comment by danlamanna** [comment]
> Did you try the troubleshooting steps?
> 
> https://help.obsidian.md/web-clipper/troubleshoot

Yes, I've tried all of them and confirmed that none of them are the issue.

**Comment by kepano** [comment]
Are you sure you are using the official Obsidian Web Clipper? 

You are saying Web Clipper version is 2.10.0 but the latest version of Obsidian Web Clipper 0.9.4

**Comment by danlamanna** [comment]
Sorry, I must have copied the version number of a different extension. I am using 0.9.4.
![image](https://github.com/user-attachments/assets/75ae6631-3116-465b-849a-aa5a1c710bbe)

**Comment by kepano** [comment]
1. Which version of the Linux Obsidian release are you using? Eg AppImage, Deb, Snap, Flatpak

2. Are you on Wayland?

**Comment by danlamanna** [comment]
> Which version of the Linux Obsidian release are you using? Eg AppImage, Deb, Snap, Flatpak

I'm using the AppImage, though I tried pointing at the extracted AppImage as well.

> Are you on Wayland?

No, X.

**Comment by kepano** [comment]
Hmmm... I'm running out of ideas. The only other thing I can think of to check would be the inspector for the Firefox extension itself and/or the service worker.

**Comment by danlamanna** [comment]
Yeah, I've looked at the inspector and seen no issues. Since it works in Brave I'm not sure there's a benefit to me building the extension locally and debugging, I'm guessing it's more likely a problem with the link between Firefox -> Obsidian URI handler?

**Comment by danlamanna** [comment]
I loaded this into the debugger and it does appear to be some sort of bug where Firefox just isn't correctly opening the `obsidian://` link. I think this issue can be closed since there's nothing actionable on your end. I'll update it when/if I figure it out for posterity.

Random question I noticed when debugging, is [this line](https://github.com/obsidianmd/obsidian-clipper/blob/a325fa782d74300508db76ad0600d09ddc6f6c47/src/utils/obsidian-note-creator.ts#L112) of code intended to be in the code path when writing to the clipboard is successful?

**Comment by kepano** [comment]
Okay your change was added to 0.9.5

**Comment by patlachance** [comment]
my 2cents for installing on Fedora 43:
- the following enabled the plugin to load, but it couldn't open Obsidian

```bash
$ ln -s /var/lib/snapd/desktop/applications/obsidian_obsidian.desktop ~/.local/share/applications/
```

- it fully worked after running 
- 
```bash
$ update-desktop-database ~/.local/share/applications
```
