### ISSUE TITLE
BUG: Not working with .AppImage on Debian

### ISSUE THREAD

**Issue by danicotillas** [obsidianmd/obsidian-clipper#138]
**Version (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox
 - Web Clipper version: 0.9.4
- Obsidian version: 1.7.5

**Describe the bug**
Web Clipper doesn't save any clip on my vault from Firefox.

**Expected behavior**
Just when clicking to have a new note created, as it happens on android.

**Your template file**
{
  "types": {
    "title": "text",
    "source": "text",
    "author": "multitext",
    "published": "date",
    "created": "date",
    "description": "text",
    "tags": "multitext",
    "titulo": "text",
    "URL": "text",
    "autoria": "text",
    "publicado": "text",
    "creado": "text",
    "comentario": "text"
  }
}

**Comment by kepano** [comment]
Please try using Web Clipper 0.9.5 and make sure you have tried the [troubleshooting](https://help.obsidian.md/web-clipper/troubleshoot) steps.

**Comment by danicotillas** [comment]
Thanks! I managed with the Flathub version.
