### ISSUE TITLE
BUG: Safari Hotkey to Activate Highlighter Mode ⌘ + ⌥ + H interferes with native "Hide All Apps Except Frontmost" Command

### ISSUE THREAD

**Issue by ArtemisFowl-san** [obsidianmd/obsidian-clipper#139]
- OS: MacOS
 - Browser : Safari
 - Web Clipper version: Version 0.9.4
- Obsidian version: 1.7.5

**Description**
Safari Hotkey to Activate Highlighter Mode ⌘ + ⌥ + H interferes with native "Hide All Apps Except Frontmost" Command. There seems to be no option to change the shortcut easily from the extension settings, compared to Chromium Browsers.

1. Go to any website
2. Try to Hide all Applications except for Safari
3. Toggles Highlighter Mode instead of hiding applications

**Expected behavior**
I would like to be able to set the keyboard shortcut for activating highlighter mode and would suggest that the default shortcut not overwrite native commands which work the same in every application.

**Comment by kepano** [comment]
Where do you see this hotkey? Safari does not support keyboard commands.

**Comment by ArtemisFowl-san** [comment]
This is a command that works system-wide 

> Command-H: Hide the windows of the front app. To view the front app but hide all other apps, **press Option-Command-H**

https://support.apple.com/en-us/102650

**Comment by kepano** [comment]
Right but what I mean is that Safari extensions don't support keyboard commands. Where do you see `Activate Highlighter Mode ⌘ + ⌥ + H` ?

**Comment by ArtemisFowl-san** [comment]
I cannot see the hotkey specified anywhere, but when I hit ⌘ + ⌥ + H in Safari when the Clipper Extension is activated, it activates highlighter mode and does not hide other applications. When I turn Clipper off in the Safari extension settings, other applications are hidden when Safari is focussed. Maybe it is something specific to my system and someone else could verify if it happens for others as well.

**Comment by kepano** [comment]
Interesting, I wonder if Apple added support in a new version of macOS without documenting it. What macOS version are you on?

**Comment by ArtemisFowl-san** [comment]
macOS Sequoia: Version 15.1

The only thing related to this I could find was from the Bitwarden Forums where they also discussed Safari Extension Hotkeys. I checked in my settings and there were not hotkeys registered to the Clipper Application.

**Comment by kepano** [comment]
This will be fixed in the next version
