### ISSUE TITLE
Ability to clip embeds

### ISSUE THREAD

**Issue by GH4TP** [obsidianmd/obsidian-clipper#140]
I'd like to be able to clip the embedded graphs (and other data types) from pages such as https://www.oecd.org/en/publications/environment-at-a-glance-indicators_ac4b8b89-en/full-report/component-46.html#chapter-d1e28710-ba61a5525b as the data is historically valuable for research purposes

**Comment by kepano** [comment]
The example here can't really be clipped because it's not an iframe, and it relies on javascript code in the web page. It would need to be captured manually as a screenshot.

**Comment by GH4TP** [comment]
I understand, thankyou @kepano 

Is clipper likely to have a 'screenshot' capability added
