### ISSUE TITLE
BUG: Linux only works with legacy mode

### ISSUE THREAD

**Issue by arejula27** [obsidianmd/obsidian-clipper#141]
**Version (please complete the following information):**
 - OS: Linux
 - Browse: firefox
 - Web Clipper version: 0.9.5
- Obsidian version: v1.7.5

**Describe the bug**
the extension does not work properly, after reading the obsidian console logs i read `content: 'Web Clipper requires Obsidian 1.7.2 or above. You …n, or enable legacy mode in Web Clipper settings.'`

**To reproduce**
1. click on the extension symbol
2. click add to obsidian

**Expected behavior**
The note should be stored but it just create an empty note (at least the title is correct).

**Your template file**
```JSON
{
  "types": {
    "title": "text",
    "source": "text",
    "author": "multitext",
    "published": "date",
    "created": "date",
    "description": "text",
    "tags": "multitext"
  }
}
```

**Comment by kepano** [comment]
Please review troubleshooting first
https://help.obsidian.md/web-clipper/troubleshoot
