### ISSUE TITLE
BUG: Clipper downloads cookie/data security information instead of the page.

### ISSUE THREAD

**Issue by Sebert81** [obsidianmd/obsidian-clipper#144]
Hi,

thank you for the clipper, works great in most cases.

However, in some instances, the clipper doesnt't download the page, but data security / cookie information text (probably a popup)..
 [Example](https://www.allianz.de/recht-und-eigentum/rechtsschutzversicherung/vertragsrecht/lieferverzug/)
 
 Regards

**Comment by kepano** [comment]
This seems to be a Readability issue. Please review troubleshooting instructions 
https://help.obsidian.md/web-clipper/troubleshoot
