### ISSUE TITLE
Feature Request: Copy Content with Properties to Clipboard. 

### ISSUE THREAD

**Issue by NopenAI** [obsidianmd/obsidian-clipper#147]
A small "Copy" button right beside "Add to Obsidian" would be much appreciated.

**Description:**

Currently, there's no straightforward way to copy content along with its properties (metadata) into the Obsidian vault. While it’s possible to copy the raw content, the associated properties are omitted. This makes it cumbersome to transfer fully formatted entries with all intended attributes.

**Proposed Solution:**

Add a "Copy with Properties" button that copies both the content and its properties in one action. This feature would improve workflow efficiency by allowing users to easily paste complete entries into their vault.

Thanks for considering this feature!

**Comment by kepano** [comment]
It will be in the next version.

**Comment by kepano** [comment]
Added in 0.9.6
