### ISSUE TITLE
Request for Support: Issue with List Conversion in Plugin

### ISSUE THREAD

**Issue by LLM391** [obsidianmd/obsidian-clipper#154]
Hi there,

I am currently using your plugin to convert text content into a list format, but I’ve encountered an issue when applying the `{{content|list}}` transformation.

While the transformation works for the first paragraph and adds the `-` symbol to it, subsequent paragraphs are not formatted with list items. This results in the text appearing as a continuous block, with only the first paragraph preceded by a `-`.

Here is an example of the content I am working with:

```
Ringbauer and colleagues (2021) examined a large global aDNA dataset, focusing on ROH (Runs of Homozygosity) across 1785 ancient individuals. They found that the degree of consanguinity was lower than expected based on anthropological literature...

[Another paragraph]
...
```

Expected behavior:
Each paragraph should be converted into a list item, like so:

- Ringbauer and colleagues (2021) examined a large global aDNA dataset, focusing on ROH...
- [Another paragraph]

However, only the first paragraph receives the `-` symbol, and the rest remain as regular text.

I’ve tried several approaches, such as using `{{content|replace("\n\n", "\n\n- ")}}` or `{{content|split("\n\n")|map("- {{value}}")}}`, but these methods still fail to apply the list format correctly to all paragraphs.

Could you please guide me on how I can ensure that each paragraph is properly converted into a list item? Alternatively, would it be possible to implement this feature in a future update of the plugin?

Thank you for your time and support. I look forward to hearing from you.

**Comment by kepano** [comment]
`{{content|split:"\n\n"|list}}`

**Comment by LLM391** [comment]
@kepano 
Thank you so much for providing the code! It has successfully resolved my issue, and I really appreciate your help.

I have one more request—would it be possible to remove another previously closed issue ([This](https://github.com/obsidianmd/obsidian-clipper/issues/153))? I mistakenly posted this same question with the wrong account earlier, and after closing it, I reposted the question using the correct account. I would like to avoid any potential privacy risks, and I would be very grateful if you could assist with this. Thank you again for your support!

**Comment by kepano** [comment]
it is not possible to delete issues afaik
