### ISSUE TITLE
Annotations on highlights and on the entire page

### ISSUE THREAD

**Issue by guyazran** [obsidianmd/obsidian-clipper#155]
I would like to have annotation functionality similar to that of [Hypothes.is](https://web.hypothes.is/). This includes adding notes to individual highlights and general notes about the entire web page.

Currently, we can either clip the website content and/or the highlights. It _is_ possible to add more information in the clipper window, but this extra info disappears if the clipper window is closed.

**Comment by kepano** [comment]
This is probably a `wontfix` because it seems out of scope for Web Clipper. The goal of Web Clipper is to get data into Obsidian where you can store information permanently.

**Comment by guyazran** [comment]
I see this issue was reopened [here](https://github.com/obsidianmd/obsidian-clipper/issues/181). adding this comment to redirect potential readers.

happy to see the team is on board with this idea :)
