### ISSUE TITLE
BUG: No content appears in note after saving it in normal mode (not legacy)

### ISSUE THREAD

**Issue by marcorichetta** [obsidianmd/obsidian-clipper#156]
**Version (please complete the following information):**

- OS: EndeavourOS (Arch)
- Browser: Firefox 133.0b7 (64-bit)
- Web Clipper version: 0.9.5
- Obsidian version: 1.7.6

**Describe the bug**

After clicking on **Add to Obsidian**, a note is created in my vault **without content**.

**Expected behavior**

I'd expect to have a note with the properties and the content.

**URLs where the bug occurs**

https://help.obsidian.md/web-clipper/troubleshoot

**To reproduce**

1. Go to https://help.obsidian.md/web-clipper/troubleshoot
2. Open the extension
3. Click on **Add to Obsidian**
4. Go to your vault
5. Open dev console https://help.obsidian.md/Help+and+support#Capture+console+logs

```js
{
    "file": "Clippings/Troubleshoot Web Clipper - Obsidian Help",
    "silent": "true",
    "clipboard": "true",
    "content": "Web Clipper requires Obsidian 1.7.2 or above. You may need to install the [early access](https://help.obsidian.md/Obsidian/Early+access+versions) version, or enable legacy mode in Web Clipper settings.",
    "action": "new"
}
```

I'm using Obsidian 1.7.6. Is it a software regression or should we update the error message?

**Template file**: Default

**Comment by marcorichetta** [comment]
It works using Legacy Mode :heavy_check_mark:

**Comment by kepano** [comment]
You can ignore the message. Your issue is likely related to clipboard access. Please review the troubleshooting steps for Linux.
