### ISSUE TITLE
BUG: Firefox Shortcut Alt + H "Get Help" interferes with Highlighter Command

### ISSUE THREAD

**Issue by andibakti** [obsidianmd/obsidian-clipper#163]
**Version:**

- OS: Windows
- Browser Firefox
- Web Clipper version: 0.9.6
- Obsidian version: 1.7.6

**Describe the bug**

Hotkey to Activate Highlighter Mode Alt + H interferes with native "Get Help" Firefox Command. There seems to be no option to change the shortcut easily from the extension settings.

**Expected behavior**

I would like to be able to set the keyboard shortcut for activating highlighter mode and would suggest that the default shortcut not overwrite native commands which work the same in every application.

**URLs where the bug occurs**

Any webpage.

**To reproduce**

1.     Go to any website
2.     Use shortcut Alt + H to activate Highlighter Mode
3.     Toggles "Get Help" Firefox shortcut instead of activating Obsidian Clipper.

**Comment by kepano** [comment]
You should be able to change commands by following the instructions in the settings. What do you suggest as a command? Unfortunately there are few available mappings.

**Comment by kepano** [comment]
Will be changed to `Alt + Shift + H`
