### ISSUE TITLE
BUG: Formatters for date variables in file name gives null

### ISSUE THREAD

**Issue by ndrezn** [obsidianmd/obsidian-clipper#164]
**Version (please complete the following information):**

- OS: MacOS
- Browser: Safari
- Web Clipper version: 0.9.6
- Obsidian version: 1.7.4

**Describe the bug**
Using date variables functions correctly:
<img width="632" alt="Screenshot 2024-11-14 at 3 51 55 PM" src="https://github.com/user-attachments/assets/0cc9cb33-50a8-4b18-b9d8-eaa570492888">
And results in:
<img width="337" alt="Screenshot 2024-11-14 at 3 52 26 PM" src="https://github.com/user-attachments/assets/88ee1172-088e-48d5-9004-8faefda1b8fd">

But, using a format as described in https://publish.obsidian.md/shellcommands/Variables/%7B%7Bdate%7D%7D fails:
<img width="627" alt="Screenshot 2024-11-14 at 3 53 01 PM" src="https://github.com/user-attachments/assets/9fcf95d3-10c5-478a-b094-1054e891f8ee">
Gives:
<img width="345" alt="Screenshot 2024-11-14 at 3 53 13 PM" src="https://github.com/user-attachments/assets/8bb566e7-36f6-41fe-82c6-68234bdc3eea">

**Expected behavior**

Expected formatters to work.

**URLs where the bug occurs**

Universal.

**To reproduce**

1. Go to Clippings "Settings"
2. Pick a template
3. Edit template "Note location" to `Clippings/{{date}}`
4. Attempt to clip a site

**Your template file**

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
{
  "schemaVersion": "0.1.0",
  "name": "Default",
  "behavior": "create",
  "noteContentFormat": "{{content}}",
  "properties": [
    {
      "name": "title",
      "value": "{{title}}",
      "type": "text"
    },
    {
      "name": "source",
      "value": "{{url}}",
      "type": "text"
    },
    {
      "name": "author",
      "value": "{{author|split:\\\", \\\"|wikilink|join}}",
      "type": "multitext"
    },
    {
      "name": "published",
      "value": "{{published}}",
      "type": "date"
    },
    {
      "name": "created",
      "value": "{{date}}",
      "type": "date"
    },
    {
      "name": "description",
      "value": "{{description}}",
      "type": "text"
    },
    {
      "name": "tags",
      "value": "clippings",
      "type": "multitext"
    }
  ],
  "triggers": [],
  "noteNameFormat": "{{title}}",
  "path": "Clippings/{{date:YYYY}}"
}
```

**Comment by kepano** [comment]
`{{date:YYYY}}` is not a valid variable. Please review the documentation.

You're looking for `{{date|date:"YYYY"}}`
