### ISSUE TITLE
BUG: new version has unexplained mandatory permissions

### ISSUE THREAD

**Issue by brian-burton** [obsidianmd/obsidian-clipper#165]
**Version (please complete the following information):**

- OS: Android 14
- Browser: Firefox 132.0.2
- Web Clipper version: 0.9.6
- Obsidian version: 1.7.6

**Describe the bug**

0.9.6 requires the new permission "Download files and read and modify the browser’s download history" with no explanation and no option to deny.

The permission implies that Web Clipper could download something and then hide that it has done so, which is behaviour I can't agree to in any add-on (nothing personal!).

I'd be happy to miss out on a specific feature that needs that permission (0.9.5 didn't require it, and I really enjoyed using Web Clipper for the few days I had it - it's a great tool), but I can't agree to any add-on that *requires* this permission to function.

**Expected behavior**

- New permissions should be explained.
- Permissions that affect transparency should be optional.

**URLs where the bug occurs**

N/A

**To reproduce**

1. Install <0.9.6 via Firefox extension site.
2. Wait for "new permission required" notification from Firefox.
3. Tap "deny".
4. Goto 2.

**Your template file**

Sorry, I can't provide a template because I've uninstalled Web Clipper. It was whatever the default was.

**Comment by kepano** [comment]
It has already been removed for 0.9.7

**Comment by brian-burton** [comment]
Thanks @kepano, installed 0.9.7 and all working fine.
