### ISSUE TITLE
Safari extension option to change ⌥⌘H (typically “Hide Others [apps]” in the Safari menu) command for engaging the Highlighter

### ISSUE THREAD

**Issue by mindfad** [obsidianmd/obsidian-clipper#168]
As the title suggests, it would be nice to have an option to change the **⌥⌘H** command to something else (as it is currently intercepted by Obsidian Webclipper to engage the page highlighter). It is the System/App-level command for hiding all other apps, which I often use in particular scenarios in Safari. I searched for this to make sure I wasn’t missing it, but alas. If so, I apologize!

**Comment by kepano** [comment]
Can I ask, where do you see this hotkey? The hotkey is Opt+Shift+H not CMD+Shift+H

**Comment by mindfad** [comment]
Apologies, I didn’t realize someone already posted this! The ⌥⌘H command to Hide Others is under the Safari (any app’s) menu.
![Screenshot 2024-11-15 at 11 53 53 AM](https://github.com/user-attachments/assets/45f72891-7953-4b43-bb4e-86415ee93da2)

**Comment by mindfad** [comment]
To clarify, ⇧⌥H toggles on and off the highlighter, but so does ⌥⌘H in exactly the same way.

**Comment by kepano** [comment]
Ok it will be fixed in the next version. This is a duplicate of #139

**Comment by mindfad** [comment]
Thank you kindly for your time and the heads! Sorry, I missed that. I’m still getting the hang of GitHub. 😊
