### ISSUE TITLE
BUG: split not behaving correctly

### ISSUE THREAD

**Issue by Oliver-De-Fusco** [obsidianmd/obsidian-clipper#172]
**Version (please complete the following information):**

- OS: Windows
- Browser Firefox
- Web Clipper version: 0.9.7

**Describe the bug**

``split`` does not split letters out when used after first and instead I have to use ``split:""``

**Expected behavior**

What did you expect to happen?

If author name is "June" then It should give "J" not "June" when using just ``split``

**URLs where the bug occurs**

I started with the FT then tested on other sites and random articles.

https://www.ft.com/content/a7288a4d-eb3a-4464-9b82-e3eb0e087930

https://www.theguardian.com/inequality/2024/nov/16/middle-class-millennials-set-to-gain-most-from-unprecedented-wealth-transfer

https://www.dailymail.co.uk/news/article-14090457/keir-starmer-dodges-farmers-protest-welsh-labour-party-conference-llandudno.html

https://www.cnbc.com/2024/11/14/stock-market-today-live-updates.html

**To reproduce**

1. Create template file
2. Go to article
3. Use template with clipper

**Your template file**

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
{
  "schemaVersion": "0.1.0",
  "name": "Bug report",
  "behavior": "create",
  "noteContentFormat": "\n# Works\n{{author|split:\" \"|first|split:\"\"|first}}\n\n\n# Does not work\n{{author|split:\" \"|first|split|first}}\n",
  "properties": [],
  "triggers": [],
  "noteNameFormat": "{{title}}",
  "path": "Clippings"
}
```

**Comment by kepano** [comment]
Fixed in [0.10.3](https://github.com/obsidianmd/obsidian-clipper/releases/tag/0.10.3)
