### ISSUE TITLE
FR: Website Favicon URL in Page Variables

### ISSUE THREAD

**Issue by greetclammy** [obsidianmd/obsidian-clipper#175]
**Describe the solution you'd like**
Include the favicon URL of the clipped website as a variable in the page properties. This would allow it to be referenced in templates.

**Use case**
With the [Auto Card Link](https://github.com/nekoshita/obsidian-auto-card-link) community plugin, having access to the favicon URL would make it possible to display the website's icon in card-style links, adding additional visual context and ensuring visual consistency across all cardlinks in one's vault:

<img width="924" alt="Screen Shot 2024-11-17 at 10 59 05" src="https://github.com/user-attachments/assets/091588d1-370c-42bf-9b45-0e387d15bb42">
<img width="924" alt="Screen Shot 2024-11-17 at 11 00 00" src="https://github.com/user-attachments/assets/a878fe7b-0a5e-4025-a8c3-6e8747848d99">

**Comment by greetclammy** [comment]
Perhaps a workaround for this could be set up somehow where, upon note creation via the clipper, the URL of the clipped webpage (added with the `{{url}}` variable) would be selected, and "Enhance selected URL to cardlink" Command Palette command would be run.

**Comment by greetclammy** [comment]
It appears that the template variable `{{selector:link[rel='icon']?href}}` works for extracting and displaying favicons. However, a dedicated page variable would ensure broader compatibility with various favicon sources, such as /favicon.ico or meta tags.

**Comment by greetclammy** [comment]
The full Auto Card Link syntax is as follows:

```
```cardlink
url: {{url}}
title: "{{title}}"
description: "{{description}}"
host: {{domain}}
favicon: {{selector:link[rel='icon']?href}}
image: {{image}}
\```
```

The backslash need to be removed as it is used to escape the triple backticks in this comment.

**Comment by kepano** [comment]
Added in [0.9.8](https://github.com/obsidianmd/obsidian-clipper/releases/tag/0.9.8).

**Comment by greetclammy** [comment]
Awesome! I ended up with this template:

```
```cardlink
url: {{url|trim}}
title: "{{title|trim|replace:("\n":" ")|replace:("  ":" ")}}"
description: "{{description|trim|replace:("\n":" ")|replace:("  ":" ")}}"
host: {{domain|trim|replace:("\n":" ")|replace:("  ":" ")}}
favicon: {{favicon|trim}}
image: {{image|trim}}
\```
```

`[replace](eplace:("\n":" ")` removes newlines because the cardlink plugin doesn't support it
`replace:("  ":" ")` removes double spaces - purely cosmetic
`trim` - just in case
`\` is used to escape triple backticks in this comment, needs to be removed
