### ISSUE TITLE
BUG: Previous highlights are deleted if you click the outer most article box

### ISSUE THREAD

**Issue by oamer1** [obsidianmd/obsidian-clipper#176]
- OS: [e.g. Windows]
- Browser [e.g. Chrome, ]
- Web Clipper version: 0.9.5
- Obsidian version: 1.7.6

** Description **
When an article consists of multiple paragraph, and accidently outer most box is clicked in highlight mode all previous highlights are deleted and substituted with with one highlight containing the entire article.

**Expected behavior**
Dont delete past highlights and add a new highlight containing the entire article.
 
 **Bug example**
 Take this chapter as an example
 [Ways of seeing]( https://www.ways-of-seeing.com/ch1)

## Screenshot 1
Initially there are 4 highlights. 
<img width="917" alt="11" src="https://github.com/user-attachments/assets/24616857-937e-4e4b-9bfb-0c740d39446f">

## Screenshot 2
When the most outer box is selected (entire article ).
<img width="946" alt="22" src="https://github.com/user-attachments/assets/b11d8bd3-3a06-453e-87ba-9fc667c5fe80">

## Screenshot 3
Previous highlights are omitted and only one highlight contain entire texts is there. 
<img width="944" alt="33" src="https://github.com/user-attachments/assets/73bc8be4-29a6-4a8d-84ec-4518b25caf1a">

**Comment by kepano** [comment]
This is not a bug. You can use CMD+z to undo.

**Comment by oamer1** [comment]
Thanks @kepano !
