### ISSUE TITLE
Fix for iOS clippings not being captured in Obsidian with Templater

### ISSUE THREAD

**Issue by tayiorbeii** [obsidianmd/obsidian-clipper#178]
I ran into an issue on iOS where the extension showed text in mobile Safari but the note in Obsidian only had the title applied then I had to paste manually in the body of the note. I realized the issue was because of some Templater settings I have for new notes.

The workaround was to use a regex in Templater to ignore the Clippings directory when applying templates:

`^(?!\/?(Clippings)\/).* (+Template)`

I cross-posted this solution to https://github.com/SilentVoid13/Templater/issues/1465#issuecomment-2481537001

(edit: feel free to close this issue, just wanted to get it indexed for anyone searching for answers)

**Comment by kepano** [comment]
Thanks!
