### ISSUE TITLE
Create a new note with note properties with behaviour option "Add to an existing note, at the bottom"

### ISSUE THREAD

**Issue by swoh816** [obsidianmd/obsidian-clipper#179]
**Describe the solution you'd like**
When creating a note using Templates, I want to Clipper to (1) create a new note **with note properties** if the note doesn't exist, and (2) add to an existing note at the bottom if the note exists. At the moment, Clipper creates a new note without note properties if the note is created with a template behaviour option "Add to an existing note, at the bottom". So, I need to add note properties manually after creating the note with the behaviour option. I think it's common for users to have note properties at the top of the note for any newly created notes, so it'd be nice to have the note properties at the top as long as the note is newly created.

Most importantly, thanks for the awesome Chrome extension!

**Comment by kepano** [comment]
This is request should be added on the Obsidian Forum since it's an Obsidian URI request, not a Web Clipper request.
