### ISSUE TITLE
Quietly clip browser pages to the note vaults instead of pop-up Obsidian pages every times.

### ISSUE THREAD

**Issue by WanRuiSpace** [obsidianmd/obsidian-clipper#190]
Whenever I clip a browser page, Obsidan creates a new note tab and pops it up to the front end, interrupting my browsing process. I hope to add a feature that allows Obsidian to remain minimized when clipping web pages. This way, I can perform the same editing in Obsdaiin after collecting a large number of web pages.

**Comment by WanRuiSpace** [comment]
Whenever I clip a browser page, Obsidan creates a new note tab and pops it up to the front end, interrupting my browsing process. I hope to add a feature that allows Obsidian to remain minimized when clipping web pages. This way, I can perform the same editing in Obsdaiin after collecting a large number of web pages.

**Comment by fabioscarsi** [comment]
> Whenever I clip a browser page, Obsidan creates a new note tab and pops it up to the front end, interrupting my browsing process. I hope to add a feature that allows Obsidian to remain minimized when clipping web pages. This way, I can perform the same editing in Obsdaiin after collecting a large number of web pages.

![CleanShot 2024-11-20 at 10 16 16@2x](https://github.com/user-attachments/assets/12610f48-7176-4be5-a458-5f9dca7646c9)

@WanRuiSpace, take a look to see if this solves your problem. Settings>General
