### ISSUE TITLE
Save all images, not just the first one

### ISSUE THREAD

**Issue by notuntoward** [obsidianmd/obsidian-clipper#193]
Apparently, the first image on a web page is saved to the Obsidian note.  This is nice but it's rarely the image I want to see again.  For example, in [Polling Is Not the Problem](https://www.nytimes.com/2024/11/19/opinion/polling-election-trump-harris.html), the first image is a large American flag, and while I am a great patriot, the flag contains no useful information.  

Instead, I'm interested in the second image, the graph of polling errors -- the Evernote, Zotero and SingleFile browser extensions do manage to save it.

For me, the best thing would be to merge this Obsidian plugin with SingleFile, similar to how the Zotero team has already done with their browser extension.  Zotero is almost always able to save reasonably complete renderings of modern web pages, along with their complex graphics

**Comment by kepano** [comment]
This is a Readability issue. See:

https://help.obsidian.md/web-clipper/troubleshoot#Some+content+is+missing

**Comment by notuntoward** [comment]
Thanks, I reported this bug there.
