### ISSUE TITLE
BUG: Instructables pages don't clip user visible content

### ISSUE THREAD

**Issue by jwhitley** [obsidianmd/obsidian-clipper#196]
**Version (please complete the following information):**

- OS: macOS 15.1.1 or iPadOS 18.1
- Browser: Safari
- Web Clipper version:0.9.8
- Obsidian version: 1.7.7

**Describe the bug**

1. Visit https://www.instructables.com/A-Simple-Drill-Press-Tray/
2. Clip the page

The visible page content, what a user would obviously expect to have clipped, isn't selected. Instead, some obscure privacy notice content embedded on the page but not normally (or ever?) visible is clipped and _none_ of the visible page content is clipped. This only happens on some pages, but not all; I haven't identified a pattern one way or another.

**Expected behavior**

The expected user visible content should be selected for clipping.

**URLs where the bug occurs**

- https://www.instructables.com/Fire-Roasted-Salsa/
- https://www.instructables.com/A-Simple-Drill-Press-Tray/

An example of a correct page on this site:

- https://www.instructables.com/Micro-Planck-3D-Printable-Low-profile-Ortholinear-/

**Your template file**

Default template is in use.

**Comment by jwhitley** [comment]
For comparison, [MarkDownload](https://apps.apple.com/us/app/markdownload/id1554029832?mt=12) clips the expected page content and none of the weird privacy text.

**Comment by jwhitley** [comment]
ugh, this bug also appears to be intermittent. After numerous incorrect clips of the drill press tray article with this extension, I just did yet another one, and it came up correctly.

I added an example of the "wrong" clip text to this gist: https://gist.github.com/jwhitley/da55ab9cef28547083e6d9103e7fb119

**Comment by kepano** [comment]
This can be solved using a template and the selector `{{selector:article|markdown}}`. Please make sure to review [Troubleshooting](https://help.obsidian.md/web-clipper/troubleshoot) instructions.

**Comment by jwhitley** [comment]
@kepano, thanks! If I understand correctly, that selector is effectively a workaround for Readability’s behavior. Is that correct? Mostly, I’m trying to understand if I should look for and/or file an upstream issue.
