### ISSUE TITLE
Unable to do a pull request to include the Catalan translation

### ISSUE THREAD

**Issue by froses** [obsidianmd/obsidian-clipper#199]
Hi, 

I tried to do a pull request to include the Catalan translation, but GitHub said I must be a Collaborator. 

Please, can you include the translation or tell me how I can do it? 

I attach the translated messages.json file. 

Thank you so much for your excellent work. I think Obsidian Clipper is, may be, the best Obsidian integration of 2024.

Best regards, 

Francesc Rosés 
[messages.json](https://github.com/user-attachments/files/17847616/messages.json)

**Comment by d-kaue** [comment]
Hello @froses, you need to [fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#forking-a-repository) this repository and create a new branch on that fork, then add your changes to this branch.

Once you've done that, follow these steps: [creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
