### ISSUE TITLE
BUG: Weird font ( Please remove “Microsoft YaHei Light” )

### ISSUE THREAD

**Issue by naokiy** [obsidianmd/obsidian-clipper#204]
**Version (please complete the following information):**

- OS: Windows (Japanese)
- Browser: Chrome and Firefox
- Web Clipper version: 0.9.8

**Describe the bug**

When used in Windows, Japanese characters are not displayed correctly.

![02b76a3730028b525052a27e8e2a1a6d3805dfd5](https://github.com/user-attachments/assets/c6f13c6f-367c-4224-94a4-a9cd599156ac)

The “ョ” (small “ヨ”) and “ッ” (small “ツ”) are written slightly higher than the other characters. However, they should be written in the lower left corner. This is a rule of the Japanese language.

This is stressful for Japanese language users.. Since “ヨ” and “ョ” and “ツ” and “ッ” are different characters, it must be easy to distinguish them.

The following other problems have also arisen.

* Only “ー” is written in serif style instead of sans serif.
* The Kanji character “選” is written in a different style from that used in Japan.

The cause of these problems is that “Microsoft YaHei Light” is specified as a font in CSS. This font is only for Chinese and is rather harmful for other languages.

**Expected behavior**

![6c17eb35a773570fbbf85b1d6e066f35f65994d1](https://github.com/user-attachments/assets/a897e3a3-f8a5-4ce5-afd8-7ceaac6e42b8)

If Microsoft YaHei Light is not specified, Japanese can be displayed correctly. ( This screenshot was taken when Microsoft YaHei Light was removed using the Developer Tool)

If you remove the Microsoft YaHei Light specification from the CSS, there should be no problem displaying Chinese. This is because the sans-serif specification will still be used.

**Places where the bug occurs**

* Setting page
* Clip dialog

**To reproduce**

1. Use Windows
2. Set the language setting to Japanese.
3. Install Webclipper to your browser
4. Open Webclipper setting page.

You will see Strange font.

**Comment by kepano** [comment]
Added in 0.10.0
