### ISSUE TITLE
BUG: (?) Notes always empty, note gets created with page title only

### ISSUE THREAD

**Issue by VOOM108** [obsidianmd/obsidian-clipper#207]
**Version (please complete the following information):**

- OS: Win 11
- BrowserArc, Chrome
- Web Clipper version: 0.9.8
- Obsidian version: 1.6.7
**Describe the bug**

Using the default template or new template, I try to clip a webpage. I see the content that is to be clipped in the preview, but sending it to Obsidian, only a new note with the page title as title is created. No properties, no content. 

The console shows no errors in the console, just a "Received URL action" message from app.js. 
![Zwischenablagebild (7)](https://github.com/user-attachments/assets/7a9a72e1-ada0-48b5-9fb2-49644a75f2a2)

I tried all kinds of webpages, makes no difference, where I try.  Also, obsidian:// is set to permanently open with Obsidian.md.

**Comment by kepano** [comment]
Web Clipper requires Obsidian 1.7.2

**Comment by VOOM108** [comment]
Thanks, I thought I was on the latest version, since it usually updates automatically in the background.
