### ISSUE TITLE
BUG: improper markdown conversion

### ISSUE THREAD

**Issue by asknet** [obsidianmd/obsidian-clipper#208]
**Version (please complete the following information):**

- OS: macOS
- Browser:  chrome
- Web Clipper version:  0.9.8
- Obsidian version: 1.7.5

**Describe the bug**

On this particular [site](https://help.salesforce.com/s/articleView?id=platform.users_license_types_communities_lightning_platform_details.htm&type=5) 
 when I use the clipper, the converted markdown has HTML table

**Expected behavior**

The converted table should be in markdown table format.

What did you expect to happen?

**URLs where the bug occurs**

Any specific web pages where the bug can be replicated.

**To reproduce**

**Your template file**

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
(paste here)
```

**Comment by kepano** [comment]
This is intentional. The table can't be converted to Markdown because it contains formatting that is not supported by Markdown. To preserve formatting it is kept as HTML.
