### ISSUE TITLE
BUG: Can't switch on some models in Interpreter

### ISSUE THREAD

**Issue by fabioscarsi** [obsidianmd/obsidian-clipper#211]
**Version (please complete the following information):**

- OS: macOS Sequoia 15.1.1
- Browser: Chrome
- Web Clipper version: 0.10.0
- Obsidian version: 1 1.7.7 (Installer 1.6.7)

**Describe the bug**

I can't switch on some models in the interpreter. When I select them (the selector becomes blue), the Clipper doesn't maintain the status chosen in memory, and they are not available for selection using the Clipper.
Consider that I was already using the interpreter function before it was documented if it can be relevant. However, the only working model for my use was OpenAI GPT-4o, so I didn't have the problem.
For some strange reason, the selectors work with "added" models.

**Expected behavior**

I wish to switch on all the default models with their selectors to be able to use them.

**URLs where the bug occurs**

Everywhere. In my system, it is a general problem.

**Comment by kepano** [comment]
Can reproduce, will be fixed in the next update

**Comment by fabioscarsi** [comment]
> Can reproduce, will be fixed in the next update

Thanks @kepano

**Comment by iLeif-de** [comment]
Sorry search only for open issues.

**Comment by kepano** [comment]
Fixed in [0.10.1](https://github.com/obsidianmd/obsidian-clipper/releases/tag/0.10.1)
