### ISSUE TITLE
BUG: Some blocks on the page are completelly ignored

### ISSUE THREAD

**Issue by Zeliret** [obsidianmd/obsidian-clipper#212]
**Version (please complete the following information):**

- OS: macOS, Sonoma 14.6.1
- Browser: Chrome 131.0.6778.86 (Official Build) (arm64)
- Web Clipper version: 0.10.0
- Obsidian version: Version 1.7.7 (Installer 1.5.3)

**Describe the bug**

When I use Web Clipper to save a web page from dndbeyond.com, one specific block is ignored and not present in the markdown. If I import the same page with the `Importer` plugin - it is present.

**Expected behavior**

The block should be present (and wrapped in callout if possible).

**URLs where the bug occurs**

https://www.dndbeyond.com/sources/dnd/free-rules/playing-the-game

<img width="1313" alt="Screenshot 2024-11-28 at 19 59 45" src="https://github.com/user-attachments/assets/a274d0bb-2f9b-4b5a-a7c7-a6e77fa5ceb0">

**To reproduce**

1. Go to https://www.dndbeyond.com/sources/dnd/free-rules/playing-the-game
2. See the very first block `Rules Glossary`.
3. Use Web Clipper to save the page.
4. The block is not present in the final markdown.

**Comment by kepano** [comment]
Please review the troubleshooting instructions:
https://help.obsidian.md/web-clipper/troubleshoot#Some+content+is+missing
