### ISSUE TITLE
BUG: The Interpreter does not allow the use of Azure OpenAI models when add a new model.

### ISSUE THREAD

**Issue by gilbertoolimpio** [obsidianmd/obsidian-clipper#214]
**Version (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Web Clipper version: 0.10.0
- Obsidian version: 1.7.7

**Describe the bug**

When I go to the Interpreter and try to insert a new model, I provide all the details of my model hosted on Azure OpenAI. However, when running the extension, the following error occurs even though all the information is correct (as verified via request in Postman).

```json
{   
    "Azure error":  
    { 
        "statusCode": 401, 
        "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired." 
    }
}
```
**Expected behavior**

The request is executed successfully.

**URLs where the bug occurs**

All URL.

**To reproduce**

1. Go to Interpreter in the extension options.
2. Click on Add Model.
3. Add the model information hosted on Azure OpenAI.
4. Execute on any page.
5. Error:
```json
{   
    "Azure error":  
    { 
        "statusCode": 401, 
        "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired." 
    }
}
```

**Your template file**
N/A

**Additional Information** 
As can be seen in the [Azure OpenAI API documentation](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#authentication), there are two types of authentication, as follows:

1. API Key authentication: For this type of authentication, all API requests must include the API Key in the `api-key` HTTP header.

2. Microsoft Entra ID authentication: You can authenticate an API call using a Microsoft Entra token. Authentication tokens are included in a request as the `Authorization` header. The token provided must be preceded by `Bearer`, for example, `Bearer YOUR_AUTH_TOKEN`. 

For the case 1 (mostly common?), the extension fails, causing the previously mentioned error due to a request problem that only uses `Authorization: Bearer ...` and don't validade if needs use `api-key` instead of `Authorization`

A proposed solution (implemented locally and validated functionality) would be to identify through a regex to validate the URL in the pattern `openai.azure.com`.

If you are interested, I can open a PR for this solution.

**Comment by elzik** [comment]
I am seeing the same problem with my Azure OpenAI model.

**Comment by kepano** [comment]
Maybe fixed in [0.10.1](https://github.com/obsidianmd/obsidian-clipper/releases/tag/0.10.1)? Give it a try.

**Comment by elzik** [comment]
Thanks for the update. I am still seeing this error:

```
Azure OpenAI error:  { "statusCode": 401, "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired." }
```

Looking at the code changes I can now see when the provider is `azure-openai`, an `api-key` header is added. The trouble is that in the settings UI when I select a provider of type `Azure OpenAI` it resets the URL to the default suggestion with placeholders. Then, when I paste my actual URL in and save it seems to reset the provider type to `Custom` which I suspect might mean that the `api-key` header never gets added.

**Comment by gilbertoolimpio** [comment]
Not yet! In my local tests, it was necessary to change the `sendToLLM` function in `interpreter.ts`.
One way to fix it, maybe, is to verify if the domain is Azure OpenAI. If true, is sended an `api-key` on the header.

[In this point](https://github.com/obsidianmd/obsidian-clipper/blob/b47ed5f7be5ae6959acfd6e43790ed4b649db853/src/utils/interpreter.ts#L107)

My code test:
```javascript
	const regex = /([\w-]+\.)?openai\.azure\.com/; //others domains if necessary.
```
...
```javascript
	const match = model.baseUrl.match(regex);
	const commmonHeaders = {
		...headers,
		"HTTP-Referer": 'https://obsidian.md/',
		"X-Title": 'Obsidian Web Clipper'
	};
	if (match) {
		headers = {
			...commmonHeaders,
			'api-key': apiKey
		};
	}else{
		headers = {
			...commmonHeaders,
			'Authorization': `Bearer ${apiKey}`
		};
	}
```

**Comment by gilbertoolimpio** [comment]
Yes, but the problem (in my case) is that the configuration of Azure OpenAI is lost when you leave the config panel. It returns to the `Custom` model and sometimes the default URL as well. You can see the following images:
1. My Configuration
![first_image](https://github.com/user-attachments/assets/039c4d7b-eefe-46f2-b872-b0d1929e1e44)

2. Getting Error:
![Screenshot 2024-12-04 at 20 04 16](https://github.com/user-attachments/assets/4f44dbe2-7139-46b3-b14a-94de1b7fdf4a)

3. When I click on the gear, we can see the custom Provider.
![third_image](https://github.com/user-attachments/assets/8859b51b-d23f-4c5b-8383-abd890a7d805)


I don't know if it is the same error as @elzik gets.

@kepano, let me know if you need more information or some logs.

tks

**Comment by gilbertoolimpio** [comment]
Works fine!
Tks
![Screenshot 2024-12-04 at 20 30 04](https://github.com/user-attachments/assets/743131b9-80ec-4b81-aa51-3c7803922d16)

**Comment by kepano** [comment]
Great!

**Comment by elzik** [comment]
The issue @gilbertoolimpio reported was the same as that I was seeing. I can also confirm that v0.10.2 fixes it. Thank you @kepano!
