### ISSUE TITLE
BUG: Can't use Anthropic models (at least without adding an OpenAI API key)

### ISSUE THREAD

**Issue by malcolmsailor** [obsidianmd/obsidian-clipper#216]
**Version (please complete the following information):**

- OS: MacOS Sequoia
- Browser: Chrome
- Web Clipper version: 0.10.0
- Obsidian version: 1.7.6

**Describe the bug**

I am trying to use Anthropic models without using OpenAI models. I have an Anthropic API key but not an OpenAI API key. I keep disabling the OpenAI models in the "Interpreter" tab, but every time I click on the Clipper extension, I get `No API key is set for OpenAI. Please set an API key in the extension settings.` and when I then return to the extension settings, all the models have been re-enabled.

It seems very possible that this issue is related to #211 

**Expected behavior**

Claude to be used as interpreter and OpenAI models to remain disabled.

**Comment by kepano** [comment]
Fixed in [0.10.1](https://github.com/obsidianmd/obsidian-clipper/releases/tag/0.10.1)
