### ISSUE TITLE
command to strip a particular tag or attribute

### ISSUE THREAD

**Issue by Kalimbim** [obsidianmd/obsidian-clipper#218]
Reverse the logic of `strip_tags` and `strip_attr` (at least as an option)

Example: I want to remove all `<a>` tags from a webpage.

I wish I could just write `strip_tags:a` in order to strip `<a>`.

But instead I have to write a list of all the tags that I want to keep, eg `strip_tags:"h2, h3, h4, p, ul, ol, li, blockquote, i, b, em, strong"`. 

The reverse logic would fit better with a common template pattern: start with `contentHtml`, then remove annoyances with `remove_html`, `strip_tags` and `strip_attr`.

**Comment by kepano** [comment]
`remove_html` can already be used as the opposite of `strip_tags`

**Comment by Kalimbim** [comment]
Different use cases. Here's a live example. Open <https://stephango.com/style> and apply this template:

```
# `remove_html`

{{selectorHtml:content|remove_html:"a"|markdown}}

# `strip_tags`

{{selectorHtml:content|strip_tags:"h2, h3, h4, p, b, i, em, strong, ol, ul, li, blockquote, figure, img, div, span"|markdown}}
```

Screenshot shows webpage with links (left), stripped tags (middle) and removed HTML (right).

![compare](https://github.com/user-attachments/assets/c8cfb261-078c-4f54-b79b-a09930ebed10)

The feature request is about making the task in the middle easier.

I want to
- select the content
- Strip the `<a>` tag (=remove the markup, but keep the text)
- convert the content to Markdown.

That's the syntax I wish we had for such a common use case: 

{{selectorHtml:content|strip_tags:"a"|markdown}} 

or 

{{selectorHtml:content|remove_tags:"a"|markdown}}

**Comment by kepano** [comment]
Ok. I don't think we should reverse the behavior of the `strip` filters since that would break all existing templates and also work differently than strip filters Twig and other templating languages. It's better to add a new filter that has the opposite behavior.

**Comment by kepano** [comment]
Added in [0.10.3](https://github.com/obsidianmd/obsidian-clipper/releases/tag/0.10.3)
