### ISSUE TITLE
Configure new line before content

### ISSUE THREAD

**Issue by astreloff** [obsidianmd/obsidian-clipper#219]
**Describe the solution you'd like**
Add checkbox "Add new line before content" or ability to configure pre-text.

**Problem**
When using behavior "Add to an existing note, at the bottom" Obsidian adds an empty line before content by default, which prevents some use cases. Tested in sandbox vault.

**Use case example**

I have predefined table header in note like this:
```
| head 1 | head 2 |
| ------- | -------- |
```

I want to add content with template:
```
| {{val1}} | {{val2}} |
```

Expected result:

| head 1 | head 2 |
| ------- | -------- |
| val1 | val2 |

Actual result (**broken table syntax with new line**):

| head 1 | head 2 |
| ------- | -------- |

| val1 | val2 |

**Comment by Airradda** [comment]
This has been responded to in https://github.com/obsidianmd/obsidian-clipper/issues/203#issuecomment-2496337308, though the name of the issue makes it hard to find.
> Obsidian URI always adds a newline when appending/prepending, it's unrelated to Web Clipper. You will need to open a feature request on the Obsidian forum if you want to have more control over that.

**Comment by kepano** [comment]
This is an Obsidian URI feature request so it should be added to Obsidian feature requests on the forum.
