### ISSUE TITLE
BUG:  Interpreter Automatically run option has no effect

### ISSUE THREAD

**Issue by iLeif-de** [obsidianmd/obsidian-clipper#221]
**Version (please complete the following information):**

- OS: MacOS 15.1.1
- Browser Safari, Chrome
- Web Clipper version: 0.10.0
- Obsidian version: 1.7.7

**Describe the bug**

When switching automatically run option off, it still runs the llm model when clicking the "Add to Obsidian Button"

**Expected behavior**
I assumed with the option off it will only call the LLM when clicking the interpret button

**URLs where the bug occurs**

Any specific web pages where the bug can be replicated.

**To reproduce**

Switch the option off ans capture any webpage

**Your template file**

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
{
  "schemaVersion": "0.1.0",
  "name": "Default",
  "behavior": "create",
  "noteContentFormat": "{{\"a summary of the page in German\"|blockquote}}\n\n{{content}}\n\n---\nOrdner: `=this.file.folder`",
  "properties": [
    {
      "name": "title",
      "value": "{{title}}",
      "type": "text"
    },
    {
      "name": "source",
      "value": "{{url}}",
      "type": "text"
    },
    {
      "name": "author",
      "value": "{{author|split:\\\", \\\"|wikilink|join}}",
      "type": "multitext"
    },
    {
      "name": "published",
      "value": "{{published|date:\\\"DD.MM.YY\\\"}}",
      "type": "date"
    },
    {
      "name": "erstellt",
      "value": "{{date|date:\\\"DD.MM.YY\\\"}}",
      "type": "text"
    },
    {
      "name": "description",
      "value": "{{description}}",
      "type": "text"
    },
    {
      "name": "tags",
      "value": "clippings",
      "type": "multitext"
    },
    {
      "name": "geändert",
      "value": "{{date|date:\\\"DD.MM.YY\\\"}}",
      "type": "text"
    }
  ],
  "triggers": [],
  "noteNameFormat": "{{title}}",
  "path": "18 Clippings"
}```

**Comment by kepano** [comment]
This is intentional. Automatically run means that it runs as soon as you open the popup.

**Comment by iLeif-de** [comment]
Ok, might be a workaround. Nevertheless the UI is a little bit misleading. So the feature for non automatically is the possibility to choose a different model, which is then the only manual step in-between.
