### ISSUE TITLE
Additional Interpreter help needed: Running ollama LLM in safari

### ISSUE THREAD

**Issue by iLeif-de** [obsidianmd/obsidian-clipper#223]
Hi,
I can't find any hint, what to use instead of `OLLAMA_ORIGINS=chrome-extension://* ollama serve` on macOS for the Safari browser. Could you add this to the help file? Also for me open, how can I use different browser on one machine?
Would be great if you add this to your Help

**Comment by kepano** [comment]
This question should be asked in the ollama repo

**Comment by iLeif-de** [comment]
Ok, thanks
