### ISSUE TITLE
unique filter for array to remove duplicates

### ISSUE THREAD

**Issue by XU-Nuo** [obsidianmd/obsidian-clipper#227]
Hi, I am trying to extract a list of image urls from the meta data in header using:
`{{selector:meta[name="og:image"]?content|image}}`, and for an unknown reason, some urls are repeated twice in the header (I did some research and it seems to be related with caching mechanism). 
So I think it would be nice to have a "distinct" or "unique" filter that can be appplied on arrary to remove duplicates.

**Comment by kepano** [comment]
Added in 0.10.3
