### ISSUE TITLE
BUG: Custom model doesn't show the delete option

### ISSUE THREAD

**Issue by natcl** [obsidianmd/obsidian-clipper#228]
**Version (please complete the following information):**

- OS: Mac OS
- Browser Safari
- Web Clipper version: 0.10.0
- Obsidian version: 1.7.7

**Describe the bug**

I added a custom model for the interpreter and cannot delete it anymore

<img width="668" alt="image" src="https://github.com/user-attachments/assets/de1cb5a2-93b9-43c8-889d-614706d9b183">

**Expected behavior**

I expect being able to delete

**Comment by fabioscarsi** [comment]
> **Version (please complete the following information):**
> 
> * OS: Mac OS
> * Browser Safari
> * Web Clipper version: 0.10.0
> * Obsidian version: 1.7.7
> 
> **Describe the bug**
> 
> I added a custom model for the interpreter and cannot delete it anymore
> 
> <img alt="image" width="668" src="https://private-user-images.githubusercontent.com/77556/392021352-de1cb5a2-93b9-43c8-889d-614706d9b183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNDgxMzEsIm5iZiI6MTczMzI0NzgzMSwicGF0aCI6Ii83NzU1Ni8zOTIwMjEzNTItZGUxY2I1YTItOTNiOS00M2M4LTg4OWQtNjE0NzA2ZDliMTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE3NDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ODVmNzVlZTAyY2ZjYTcyZWZlZDA3ZjQ4ODA0YzJhODg2YjcyNWEwYzU1OGQwZTNhNjI5MGM2NGQ4ZDAxNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qINyFYoUFr1QodqHceX17pS0iBBtSkED2fahWDckFC0">
> **Expected behavior**
> 
> I expect being able to delete

I have the same lack after having set Claude by Anthropic as a custom model.

**Comment by natcl** [comment]
So I checked a bit more and found the source of the issue, it's because the check is done on provider and I entered OpenAI:
https://github.com/obsidianmd/obsidian-clipper/blob/f220666dcca0c46b786afa1659284cf43ff31cb0/src/managers/interpreter-settings.ts#L109

I assume the check might need to be done on the name or perhaps have a special hidden property for built-in models.

**Comment by kepano** [comment]
Fixed in [0.10.1](https://github.com/obsidianmd/obsidian-clipper/releases/tag/0.10.1)
