### ISSUE TITLE
BUG: Darkmode for template dropdown does not work

### ISSUE THREAD

**Issue by JoPe72** [obsidianmd/obsidian-clipper#233]
**Version (please complete the following information):**

- OS: Windows
- Browser Microsoft Edge and Chrome
- Web Clipper version: 0.10.1
- Obsidian version: 1.7.7

**Describe the bug**

When I drop down the list of templates on a browser in Dark Mode, the list is white but the text (I think is for Dark mode which makes it hard to see)

**Expected behavior**

What did you expect to happen? It should be dark

**URLs where the bug occurs**

Any specific web pages where the bug can be replicated.
Everywhere

**To reproduce**
Click on the addin in edge
Click on the double arrows for a list of templates

![image](https://github.com/user-attachments/assets/cc83e16c-95b6-4ce9-9110-9ce1ccfc73eb)
![image](https://github.com/user-attachments/assets/0a9da275-8abf-4c37-92b4-ecf5b90ddbf0)

**Your template file**

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
(paste here)
```

**Comment by kepano** [comment]
Do other dropdowns display correctly in dark mode? E.g. in settings?

**Comment by JoPe72** [comment]
Yes, they do

![image](https://github.com/user-attachments/assets/c2aec434-defe-4cce-8bf5-2f045525a281)

**Comment by kepano** [comment]
Fixed in [0.10.3](https://github.com/obsidianmd/obsidian-clipper/releases/tag/0.10.3)
