### ISSUE TITLE
Integrating the Gemini API into the Obsidian Interpreter

### ISSUE THREAD

**Issue by Evantix** [obsidianmd/obsidian-clipper#234]
### Integrating the Gemini API into the Obsidian Interpreter

Unfortunately, I often encounter an error message stating, {"error":{"message":"Request too large for model," indicating that the pages I work with exceed the model's capacity. Even when I adjusted the **Default interpreter context** some of the pages are still to big.

Integrating the Gemini API into the Obsidian Interpreter could significantly enhance its capabilities, particularly given Gemini's extensive token window. Leveraging Google's API is ideal for processing and clipping large, detail-rich pages. Additionally, Gemini API it currently remains free, which adds to its appeal.

**Comment by kepano** [comment]
Gemini API should already work.

Can you provide more detail about your configuration?

- Provider configuration (don't share your API key)
- Model configuration
- Interpreter context
- Pages you are trying to clip

**Comment by kepano** [comment]
I just tested, and it seems to work fine. You can try with these settings:

- Base URL: `https://generativelanguage.googleapis.com/v1beta/chat/completions`
- Model: `gemini-1.5-flash`

**Comment by Evantix** [comment]
I just realized that my API endpoint was incorrect, which is why it wasn't functioning properly. 

Everything is working perfectly now.

Thank you!

**Comment by fabioscarsi** [comment]
> I just realized that my API endpoint was incorrect, which is why it wasn't functioning properly.
> 
> Everything is working perfectly now.
> 
> Thank you!

@Evantix I've been working with Gemini LLMs in Obsidian Web Clipper for several days. Right now they give the best results with some complex prompt I use in my templates (something like an adapted version of  Fabric's "extract wisdom" pattern https://github.com/danielmiessler/fabric/tree/main/patterns/extract_wisdom), a tagging prompt using the Library of Congress Classification as reference (https://www.loc.gov/catdir/cpso/lcco/), ad so on ...

To manage the complexity of this prompts and to manage several simultaneous prompts in a template i had to use the top LLMs and Gemini are giving the best results.
So, if you didn't find them out, this are the model IDs of Gemini actual top models:
- gemini-exp-1114
- gemini-exp-1121
- gemini-1.5-pro-latest
The first two are experimenta but work surprisingly well and the last one is the most recent stable production version.

I apologize if you alredy knew all the IDs.

**Comment by fabioscarsi** [comment]
@kepano by the way, before the last upgrade I was able to use Antrophic with custom settings.
But they don't work anymore after upgrading to the last version 0.10.2.
These are the screenshots of my settings without the API key.
Any idea of what I am doing wrong?

![CleanShot X 2024-12-06 17 53 37](https://github.com/user-attachments/assets/74bc2fd1-1142-4024-87ed-1a6e507c9597)
![CleanShot X 2024-12-06 17 54 32](https://github.com/user-attachments/assets/1f24304b-1216-43a6-a3c6-5fcb58ca9b20)

**Comment by kepano** [comment]
@fabioscarsi I just tested with your settings and it works for me. This repo should be used for bug reports and feature requests. For troubleshooting please use our official channels. Your best bet is the Discord channel. Also you'll need to provide steps to reproduce and detail what the error is.

**Comment by fabioscarsi** [comment]
> @fabioscarsi I just tested with your settings and it works for me. This repo should be used for bug reports and feature requests. For troubleshooting please use our official channels. Your best bet is the Discord channel. Also you'll need to provide steps to reproduce and detail what the error is.

Thanks @kepano. Considering it worked before the upgrade, I thought it was a bug ...
