### ISSUE TITLE
Support for Converting ISO 8601 Durations to Human-Readable Format

### ISSUE THREAD

**Issue by jldiaz** [obsidianmd/obsidian-clipper#239]
**Context:**

I frequently use Obsidian Web Clipper to extract information from web pages, including video metadata like duration. Many websites, such as YouTube, provide video durations in the ISO 8601 format—for example, `PT6702S` represents a duration of 6702 seconds.

Currently, the available filters (`slice`, `date`, `calc`) don't allow for an easy conversion of this ISO 8601 duration into a human-readable format like `HH:mm:ss`. Attempts to manipulate the string and parse it using the `date` filter lead to issues with time zone adjustments, causing inaccurate results.

**Feature Request:**

I propose adding a new filter or enhancing existing ones to support the conversion of ISO 8601 duration strings directly into human-readable time formats without time zone adjustments.

**Proposed Solution:**

- **New Filter (e.g., `duration`):**
  - Parses ISO 8601 duration strings and formats them according to a specified pattern.
  - Example usage: `{{schema:@VideoObject:duration|duration:"HH:mm:ss"}}` would output `01:51:42` for `PT6702S`.

**Thank you for considering this feature request!**

**Comment by kepano** [comment]
Will be in 0.10.5
