### ISSUE TITLE
Windows: Nothing is saved when I click "Add to Obsidian"

### ISSUE THREAD

**Issue by aoout** [obsidianmd/obsidian-clipper#24]
windows 10, edge brower.
obsidian v1.6.7.
no any plugins.

**Comment by Moyf** [comment]
It seems that when clpping long/complex text, the Obsidian would do nothing.
I'm not sure if it's related to the Obsidian URL Scheme?

**Comment by viowy** [comment]
Win‘s Edge and Vivaldi are failed.

**Comment by kepano** [comment]
Two things to look at:


1. Do you see any errors in edge://extensions/manage ?

2. Go to developer tools for the current page. When you click "Add to Obsidian" does a URI appear?

**Comment by 3217333857** [comment]
the same problem, could not save whole text and long text.  Three paragraphs could be saved, but I choose five paragraphs, there is no response.

**Comment by mffseal** [comment]
same problem here.
edge: 128.0.2739.67.
system: Windows 11  22631.4169

**Comment by 3217333857** [comment]
> the same problem, could not save whole text and long text. Three paragraphs could be saved, but I choose five paragraphs, there is no response.
same problem appears on my another computer
browser:edge、Vivaldi 
system:win11

**Comment by kepano** [comment]
It's likely a limit on the URI length. What happens if you remove content from the note body before saving?

**Comment by 3217333857** [comment]
> It's likely a limit on the URI length. What happens if you remove content from the note body before saving?↳

What do you mean? If remove the content, every web could be saved. There is a limit on the URI length.

**Comment by kepano** [comment]
Oh then that's the problem, at least for your case. In a future update we'll save the content a different way, however this will require Obsidian 1.7+

**Comment by 3217333857** [comment]
> Oh then that's the problem, at least for your case. In a future update we'll save the content a different way using the clipboard rather than URI, however this will require Obsidian 1.7+↳

Thank you, hoping for 1.7+. By the way, what is your browser? Is there a browser do not have this problem? This plugin is so exciting, I could not wait to use it.

**Comment by kepano** [comment]
Chrome, Brave, Firefox all seem to be working as expected

**Comment by 3217333857** [comment]
> Chrome, Brave, Firefox all seem to be working as expected↳

the same problem on chrome

**Comment by cayguu** [comment]
same problem here.
errors in edge://extensions/  is: Error extracting page content: Error: Could not establish connection. Receiving end does not exist.

**Comment by kepano** [comment]
This should now work if you update to Obsidian 1.7.2 and activate beta features in Web Clipper → General settings.

**Comment by kepano** [comment]
Closing in favor of #51 since it seems to be causing confusion
