### ISSUE TITLE
BUG: Ollama Requests seem to be missing page context?

### ISSUE THREAD

**Issue by qfettes** [obsidianmd/obsidian-clipper#248]
**Version (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Web Clipper version: 0.10.3
- Obsidian version: [e.g. 1.7.5]

**Describe the bug**

I'm using obsidian web clipper with ollama models. I've added chrome-extensions as an origin via `launchctl setenv OLLAMA_ORIGINS "chrome-extension://*"`. I've turned on debug logging, and it appears that requests are reaching ollama, but do not have any page context with the request (see image)

This is the ollama logging after sending a request on the landing page for this github repo

```
time=2024-12-10T10:36:19.522-08:00 level=WARN source=sched.go:137 msg="mllama doesn't support parallel requests yet"
time=2024-12-10T10:36:19.522-08:00 level=DEBUG source=sched.go:575 msg="evaluating already loaded" model=/Users/qfettes/.ollama/models/blobs/sha256-11f274007f093fefeec994a5dbbb33d0733a4feb87f7ab66dcd7c1069fef0068
time=2024-12-10T10:36:19.537-08:00 level=DEBUG source=prompt.go:77 msg="truncating input messages which exceed context length" truncated=2
time=2024-12-10T10:36:19.537-08:00 level=DEBUG source=routes.go:1464 msg="chat request" images=0 prompt="<|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant. Please respond with one JSON object named `prompts_responses` — no explanatory text before or after. Use the keys provided, e.g. `prompt_1`, `prompt_2`, and fill in the values. Values should be Markdown strings unless otherwise specified. Make your responses concise. For example, your response should look like: {\"prompts_responses\":{\"prompt_1\":\"tag1, tag2, tag3\",\"prompt_2\":\"- bullet1\n- bullet 2\n- bullet3\"}}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{\"prompts\":{\"prompt_1\":\"A summary of the page. Cover everything important, be verbose if needed.\",\"prompt_2\":\"provide a title for this page in 10 words or less\",\"prompt_3\":\"Source of this page: the group, organization or individual. If multiple, use as a comma-separated list\",\"prompt_4\":\"Authors of this page\",\"prompt_5\":\"1 to 5 words in lowercase describing the type of this page. a type can be multiple words if hyphenated\",\"prompt_6\":\"A brief summary of this page\"}}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
time=2024-12-10T10:36:19.538-08:00 level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=315 prompt=238 used=237 remaining=1
[GIN] 2024/12/10 - 10:36:24 | 200 |  4.878372708s |       127.0.0.1 | POST     "/api/chat"
time=2024-12-10T10:36:24.369-08:00 level=DEBUG source=sched.go:407 msg="context for request finished"
time=2024-12-10T10:36:24.369-08:00 level=DEBUG source=sched.go:339 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/Users/qfettes/.ollama/models/blobs/sha256-11f274007f093fefeec994a5dbbb33d0733a4feb87f7ab66dcd7c1069fef0068 duration=5m0s
time=2024-12-10T10:36:24.369-08:00 level=DEBUG source=sched.go:357 msg="after processing request finished event" modelPath=/Users/qfettes/.ollama/models/blobs/sha256-11f274007f093fefeec994a5dbbb33d0733a4feb87f7ab66dcd7c1069fef0068 refCount=0
```

This is the config for my template:
![Screenshot 2024-12-10 at 10 40 41 AM](https://github.com/user-attachments/assets/80ec423d-cd50-494c-8c74-5851153381a0)

These are my interpreter settings (I haven't modified the default context):
![Screenshot 2024-12-10 at 10 41 40 AM](https://github.com/user-attachments/assets/b8ee28cf-b45c-4b9e-bfd4-49afd5d71c2c)

**Expected behavior**

The page content should be passed to the ollama model with the prompts.

**URLs where the bug occurs**

Every url. You can use https://github.com/obsidianmd/obsidian-clipper

**To reproduce**

1. Launch ollama allowing chrome extension requests
3. Go to any url
4. Click on the web clipper and use the template
5. View logs in terminal where you ran ollama server
6. See error

**Your template file**

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
{
  "schemaVersion": "0.1.0",
  "name": "AI Raycast Bookmark + Content",
  "behavior": "create",
  "noteContentFormat": "# Summary\n{{\"A summary of the page. Cover everything important, be verbose if needed.\"}}\n\n# Content\n{{content}}",
  "properties": [
    {
      "name": "created",
      "value": "{{date}}",
      "type": "date"
    },
    {
      "name": "title",
      "value": "{{title}}",
      "type": "text"
    },
    {
      "name": "saved",
      "value": "{{date}}",
      "type": "text"
    },
    {
      "name": "source",
      "value": "{{url}}",
      "type": "text"
    },
    {
      "name": "publisher",
      "value": "{{\\\"Source of this page: the group, organization or individual. If multiple, use as a comma-separated list\\\"|split:\\\", \\\"|wikilink|join}}",
      "type": "text"
    },
    {
      "name": "author",
      "value": "{{\\\"Authors of this page\\\"|split:\\\", \\\"|wikilink|join}}",
      "type": "multitext"
    },
    {
      "name": "published",
      "value": "{{published}}",
      "type": "date"
    },
    {
      "name": "read",
      "value": "0",
      "type": "checkbox"
    },
    {
      "name": "tags",
      "value": "bookmark,{{\\\"1 to 5 words in lowercase describing the type of this page. a type can be multiple words if hyphenated\\\"}}",
      "type": "multitext"
    },
    {
      "name": "description",
      "value": "{{\\\"A brief summary of this page\\\"}}",
      "type": "text"
    }
  ],
  "triggers": [],
  "noteNameFormat": "{{\"provide a title for this page in 10 words or less\"}} ",
  "path": "/"
}
```

**Comment by kepano** [comment]
I am not able to reproduce this issue.

1. Did you remember to run the model? You are just showing screenshots of the server.
2. What is the Base URL in your Ollama provider?
3. What model are you using? Does this happen with all models?
4. What happens if you delete the default interpreter context (reset it to blank)

**Comment by qfettes** [comment]
> Did you remember to run the model? You are just showing screenshots of the server.

Yes, this is an issue whether or not I run the model

> What is the Base URL in your Ollama provider?

http://127.0.0.1:11434/api/chat

> What model are you using? Does this happen with all models?

All models. This example was llama3.2-vision:11b

> What happens if you delete the default interpreter context (reset it to blank)

I still see no page context in the cli window with the interpreter, and the llm results are not relevant to the page

**Comment by qfettes** [comment]
I changed the interpreter context to {{content}} and I see the relevant content in the server. It seems like there is some issue with the default interpreter context?

**Comment by qfettes** [comment]
I changed the interpreter context to {{content}}, highlighted the text under Describe your bug in my original post, and now I see the following context being passed to the interpreter:

```
time=2024-12-10T12:17:41.642-08:00 level=DEBUG source=routes.go:1464 msg="chat request" images=0 prompt="<|im_start|>system\nYou are a helpful assistant. Please respond with one JSON object named `prompts_responses` — no explanatory text before or after. Use the keys provided, e.g. `prompt_1`, `prompt_2`, and fill in the values. Values should be Markdown strings unless otherwise specified. Make your responses concise. For example, your response should look like: {\"prompts_responses\":{\"prompt_1\":\"tag1, tag2, tag3\",\"prompt_2\":\"- bullet1\n- bullet 2\n- bullet3\"}}<|im_end|>\n<|im_start|>user\n**Describe the bug**\n\nI'm using obsidian web clipper with ollama models. I've added chrome-extensions as an origin via `launchctl setenv OLLAMA_ORIGINS \"chrome-extension://*\"`. I've turned on debug logging, and it appears that requests are reaching ollama, but do not have any page context with the request (see image)\n\nThis is the ollama logging after sending a request on the landing page for this github repo\n\n{\"prompts\":{\"prompt_1\":\"A summary of the page. Cover everything important, be verbose if needed.\",\"prompt_2\":\"provide a title for this page in 10 words or less\",\"prompt_3\":\"Source of this page: the group, organization or individual. If multiple, use as a comma-separated list\",\"prompt_4\":\"Authors of this page\",\"prompt_5\":\"1 to 5 words in lowercase describing the type of this page. a type can be multiple words if hyphenated\",\"prompt_6\":\"A brief summary of this page\"}}<|im_end|>\n<|im_start|>assistant\n"
time=2024-12-10T12:17:41.655-08:00 level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=363 prompt=335 used=334 remaining=1
```

There appears to be some issue when passing the full html to ollama?

**Comment by qfettes** [comment]
It appears that the issue is indeed length, or including multiple images. If I highlight a single image, it is summarized as expected. If I highlight the entire page or multiple images, I see the following message in the cli which I ran ollama serve: 

```
time=2024-12-10T13:22:00.411-08:00 level=DEBUG source=prompt.go:77 msg="truncating input messages which exceed context length" truncated=2
```

When I receive this message, I see no page context being passed to ollama

**Comment by kepano** [comment]
It's possible that the context you're trying to pass exceeds the token limit.

**Comment by AriTheElk** [comment]
I'm also seeing the same thing. I tried using the custom context @kepano posted on reddit for the YouTube transcript clip:

```
{{description}}

{{selectorHtml:ytd-engagement-panel-section-list-renderer[visibility$=\"EXPANDED\"] #segments-container|strip_tags:"h2,ytd-transcript-segment-renderer"|replace:"ytd-transcript-segment-renderer":"li"|markdown}}
```

But all I get is a simple sentence like "Description will go here" or something along those lines, which is definitely an LLM response but no indication of receiving any actual page context

**Comment by kepano** [comment]
The problem is context length. Ollama defaults to 2048 tokens, which is the total limit for the message + response. Ollama will fail silently if this limit is exceeded.  I think it's because this is set at the model level not at the server level.

It looks like this issue has been documented on the Ollama repo a few times, here's the most useful comment about it:
https://github.com/ollama/ollama/issues/5965#issuecomment-2252354726

One option in Web Clipper is to use the `slice` filter on your context variable, e.g. `{{content|slice:0,1000}}` — this works reliably for me, but obviously it may trim some useful context. You can also try messing with the Ollama context options described in the link above.

Note that the models themselves will also have a context window and may fail silently.

**Comment by AriTheElk** [comment]
Confirming that `{{content|slice:0,1000}}` fixed it for me, good to know 👍  I'll play around with raising the token limit on Ollama. Seems like it might be as easy as tweaking the [num_ctx](https://github.com/ollama/ollama/issues/3644#issuecomment-2057646417) option

**Comment by kepano** [comment]
This should be improved in 0.10.6
