### ISSUE TITLE
Add option to remove empty spaces when adding to existing note

### ISSUE THREAD

**Issue by gsarig** [obsidianmd/obsidian-clipper#252]
**Describe the solution you'd like**
So, the scenario that I try to implement is this: I have a note which only includes a table, and I would like to add specific clippings to that note, as additional rows on that table. The Web Clipper template is like 
```
| {{var1}} | {{var2}} | {{var3}} |
```
The problem with that is that when the new content gets appended to the note, there is a blank line before it, which I have to manually remove, otherwise the new entry is in the form of a paragraph instead of a table row. It would be nice if there would be an option to append data to notes while stripping out the preceding blank line, as populating tables with content from clippings could be a powerful feature. 

I would also be interested to know if there is an event that I could listen to, that gets triggered when the new clipping gets added to the note. That way, I could probably strip it myself.

**Comment by jldiaz** [comment]
Duplicated: #219 

It cannot be done from the clipper.
