### ISSUE TITLE
Options for Colour Highlights

### ISSUE THREAD

**Issue by jun6lee** [obsidianmd/obsidian-clipper#268]
I'll share my use case with you which I've used for Apple Books:

Green Highlights — Conclusive Facts
Yellow Highlights — Examples
Blue Highlights — Questions
Pink Highlights — The Premium post-it note worthy quote.
Underlines — Titles / Subtitles

This then allows me to organize my highlights and make useful notes from them more efficiently:

![CShot 2024-12-17 at 15 48 39@2x](https://github.com/user-attachments/assets/14263e53-93ed-4158-9d4a-349845668da9)

My request is that in your roadmap, if you could add such function (aside annotation), this would be a great addition for me, but I so feel the usefulness of this would be to a fairly wide user-base.

Currently, I'm using glasp.co and exporting out per webpage .md files weekly for this purpose.

**Comment by kepano** [comment]
This is unlikely because Markdown and Obsidian don't allow multiple colors for highlights.

**Comment by greetclammy** [comment]
Markdown may not but HTML does. For example, I use `<mark>` tags in Obsidian for more colors:

<img width="960" alt="Screen Shot 2024-12-21 at 12 51 49" src="https://github.com/user-attachments/assets/c63e9d91-5ce2-4885-a4d5-a8d30bdfe81e" />


But I understand that implementing something like into the clipper would be a hack. Nevertheless, I support this request 👍

**Comment by kepano** [comment]
I don't think it makes sense for the official Web Clipper because it should mirror Obsidian's focus on interoperable Markdown.
