### ISSUE TITLE
Remove highlights individually

### ISSUE THREAD

**Issue by ReCodeRa** [obsidianmd/obsidian-clipper#279]
Congratulations! Very nice tool and progress :D I am using Diigo and there are two features I miss in Obsidian-clipper: 

1. **Individual highlight management** - I would love to have a hoover-over menu where I can change highlighter color, add a note or completely remove individual highlight. Please check Diigo for it. 

![Diigo contex bar](https://github.com/user-attachments/assets/2aae7b47-9849-442b-b11b-4b0d2fa4d1fe)

2. **PDF highlighting** - although this could be solved by using Pdf++ and/or Zotero directly in Obsidian.

**Comment by kepano** [comment]
PDF highlighting is out of scope for Web Clipper. This is better handled using other tools or possibly Obsidian itself in the long term.

The other requests are duplicative of #181 and #268
