### ISSUE TITLE
BUG: After opening the local application, the clipper web page does not appear after the obsidian v1.7 web clipper chrome plugin

### ISSUE THREAD

**Issue by ice345** [obsidianmd/obsidian-clipper#284]
**Version (please complete the following information):**

ubuntu 22.04LTS 
gnome 42.9
kernel linux 6.8.0

- OS: [e.g. Windows] linux(Ubuntu)
- Browser [e.g. Chrome, Firefox] Chrome
- Web Clipper version: [e.g. 0.9.5] 0.10.5
- Obsidian version: [e.g. 1.7.5] 1.7.7

**Describe the bug**

A clear and concise description of the bug. If applicable, add screenshots to help explain the problem.

In linux (ubuntu), I use chrome to click the obsidian web clipper plug-in and open the obsidian local warehouse. It can be opened normally, but there is no web page md file

**Expected behavior**

Create an md file after opening the warehouse normally

What did you expect to happen?

**URLs where the bug occurs**

https://course.rs/about-book.html

Any specific web pages where the bug can be replicated.

**To reproduce**

1. Go to '...' https://course.rs/about-book.html
2. Click on '....' Obsidian web clipper
3. Scroll down to '....' Open my reposite

**Your template file**

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
(paste here)
```

**Comment by kepano** [comment]
Please follow the troubleshooting instructions for Linux and use the Discord channel for support on this issue
https://help.obsidian.md/web-clipper/troubleshoot
