### ISSUE TITLE
BUG: `clip highlights` will still process the entire content of the webpage

### ISSUE THREAD

**Issue by ice345** [obsidianmd/obsidian-clipper#287]
**Version (please complete the following information):**

ubuntu 22.04LTS 
gnome 42.9
kernel linux 6.8.0
I have add %u in my obsidian.desktop in Exec line

- OS: [e.g. Windows] linux(Ubuntu)
- Browser [e.g. Chrome, Firefox] Chrome
- Web Clipper version: [e.g. 0.9.5] 0.10.5
- Obsidian version: [e.g. 1.7.5] 1.7.7

**Describe the bug**

A clear and concise description of the bug. If applicable, add screenshots to help explain the problem.

**I have checked the issue about highlight, but I didn't find a solution.**

After highlighting a part, clicking `clip highlights` will still process the entire content of the webpage, whether you click `Add to obsidian` or click `Copy to pasteboard`, it will be the entire content of the webpage

**Expected behavior**

Only process the parts I highlighted, not the entire page

What did you expect to happen?

**URLs where the bug occurs**

https://course.rs/about-book.html and other web

Any specific web pages where the bug can be replicated.

**To reproduce**

1. Go to '...' https://course.rs/about-book.html
2. Click on '....' Obsidian web clipper
3. Scroll down to '....' Open my reposite

**Your template file**

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
(paste here)
```

**Comment by kepano** [comment]
What seeing are you using in Web Clipper settings → Highlighter → Clip behavior ?

**Comment by ice345** [comment]
> What setting are you using in Web Clipper settings → Highlighter → Clip behavior ?您在 Web Clipper 设置中使用了什么设置→ Highlighter → Clip 行为？

The default settings,like:

![Snipaste_2024-12-26_09-11-15](https://github.com/user-attachments/assets/0c320b30-b0fb-4e97-ac02-9f8b6ddd0d69)

**Comment by ice345** [comment]
> What setting are you using in Web Clipper settings → Highlighter → Clip behavior ?

for you an error example picture:

![截图 2024-12-27 11-00-22](https://github.com/user-attachments/assets/e7df2c48-a9b6-403c-ad37-ee06228e718f)

**Comment by ice345** [comment]
> > What setting are you using in Web Clipper settings → Highlighter → Clip behavior ?您在 Web Clipper 设置中使用了什么设置→ Highlighter → Clip 行为？
> 
> The default settings,like:
> 
> ![Snipaste_2024-12-26_09-11-15](https://private-user-images.githubusercontent.com/143070544/398609519-0c320b30-b0fb-4e97-ac02-9f8b6ddd0d69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNjYxNTMsIm5iZiI6MTczNTM2NTg1MywicGF0aCI6Ii8xNDMwNzA1NDQvMzk4NjA5NTE5LTBjMzIwYjMwLWIwZmItNGU5Ny1hYzAyLTlmOGI2ZGRkMGQ2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQwNjA0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGYyZjIxYjgyZTMzNGUzNGI5MWE4NjRjMGM5MTg2ODhmYWI0NWY0MGRmMWUzNjVlZGQ4YWQwNDQ1NTNjZjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WDWKJgfJdB7LvfZHfgC6uA-Ac5gBFcFyMW85t-tNzhQ)



It is my fault, I do not know that it should be replaced the contents. 😢
