### ISSUE TITLE
Add safari origin for ollama

### ISSUE THREAD

**Issue by jakejx** [obsidianmd/obsidian-clipper#288]
The current [documentation](https://help.obsidian.md/web-clipper/interpreter) for Ollama only includes the origin for Chrome and Firefox. It took me awhile to find that that the correct origin for Safari is `safari-web-extension://*`. It would be good to include it in the docs. Thanks.

**Comment by kepano** [comment]
The best place to make changes to the Obsidian docs is on the help site repo itself. You can also submit your edits there: 
https://github.com/obsidianmd/obsidian-help

**Comment by jakejx** [comment]
Thanks, didn't know there was a docs repo. Submitted a PR there.
