### ISSUE TITLE
Question: How to clip only text content and no images

### ISSUE THREAD

**Issue by amperag** [obsidianmd/obsidian-clipper#33]
Hi, I'm loving the new clipper extension so far! Works flawlessly for me using Firefox v130.0 and Obsidian v1.6.7.

How is it possible to just get the **text** from `{{content}}` without **images**?

Thanks!

---

Edit, my template

```
# {{title}}
#source #clippings

**{{description}}**

{{content}}
```

**Comment by kepano** [comment]
Okay I added the `stripmd` filter, see readme. It will be in the next version.

**Comment by kepano** [comment]
Added to 0.4.1 which will be available when approved by the extension stores.
