### ISSUE TITLE
Question: How to customize the date's format

### ISSUE THREAD

**Issue by Moyf** [obsidianmd/obsidian-clipper#34]
> date converts a date to the specified format such as date:"YYYY-MM-DD", [see reference](https://day.js.org/docs/en/display/format).

Hi, I was wondering how to give the format param to `{{date}}`?

Trid `{{date|YYYY}}` and `{{date:YYYY}}`, not work.

For example, if I want the `YYMMDD_` format's date, how can I achive it?

**Comment by kepano** [comment]
There is the {{date}} variable (meaning today) and the `date` filter to convert dates. So you need to do `{{date|date:YYMMDD_}}`
