### ISSUE TITLE
[FR] Support variables for note location

### ISSUE THREAD

**Issue by Moyf** [obsidianmd/obsidian-clipper#36]
Hello!

Just tried to use the `year-month` format as the folder structure to better organize my notes:
![image](https://github.com/user-attachments/assets/fc7bd0db-ffed-4842-b9d4-156196ee5e55)

However, it seems that currently the **Note location** does not support variables:

![image](https://github.com/user-attachments/assets/a70943f9-df4a-4098-bfc2-48e2c39197a8)

![image](https://github.com/user-attachments/assets/3580749f-14c8-49ed-94ad-650a99ed0742)

Could you please consider adding support for using variables in Location field as well?

**Comment by kepano** [comment]
Will be in the next version
