### ISSUE TITLE
`date` variable lacks of the time data.

### ISSUE THREAD

**Issue by Moyf** [obsidianmd/obsidian-clipper#44]
Hello!

It appears that the `date` variable currently does not include the `time` component. 
As a result, when I use `{{date|date:YYYY-MM-DDTHH:mm}}`, the time portion defaults to `000000`.

![image](https://github.com/user-attachments/assets/5c7a1fa3-e2e2-47a8-94a6-0be0729d2a62)

Could you please consider incorporating the current time into the `date` variable, or alternatively, introducing a new variable called `datetime`?

**Comment by kepano** [comment]
Will be fixed in 0.4.8 with the addition of `{{time}}` as a shorthand, and the ability to use date filters on `{{date}}` and `{{time}}` for more granular control
