### ISSUE TITLE
(bug): Clipper errors out on some Internet Archive directory pages

### ISSUE THREAD

**Issue by marcus-crane** [obsidianmd/obsidian-clipper#45]
Hey there,

I'm not entirely sure how broadly the clipper should support the web but I noticed some instances where it crashes rather than displaying the expected message that it can't parse the page content.

Specifically some of the Internet Archive's directory pages such as https://archive.org/download/spotify-v-8.10.9.722-latest.

Some of them parse fine with others display `An error occurred: t.childNodes[a].getAttribute is not a function`.

I don't actually have any use case for clipping these pages to be clear, I actually happened to accidentally trigger the extension and thought the error was a little unexpected so you might be interested to know about it.

Thanks!

**Comment by kepano** [comment]
This should be fixed in 0.4.9

**Comment by marcus-crane** [comment]
Very nice. Thanks!

![CleanShot 2024-09-23 at 12 46 53](https://github.com/user-attachments/assets/ed19720e-8213-48d3-97d4-6b2ff2e6b7b8)
