### ISSUE TITLE
Brave browser: nothing happens when I click "Add to Obsidian"

### ISSUE THREAD

**Issue by benschifman** [obsidianmd/obsidian-clipper#48]
Windows 11
Brave browser
Obsidian v1.6.7

Exciting to get this working - thanks!

**Comment by benschifman** [comment]
Updating to note that it does seem to work on shorter pages, as with the similar issue reported for Edge browser. Looks like this will be fixed with a future update so I can close this or leave it open, whatever the mods thinks makes sense. Thanks!

**Comment by marcus-crane** [comment]
Very nice. Thanks!

![CleanShot 2024-09-23 at 12 46 53](https://github.com/user-attachments/assets/ed19720e-8213-48d3-97d4-6b2ff2e6b7b8)
