### ISSUE TITLE
Suggestion: Context Menu Item

### ISSUE THREAD

**Issue by brpaz** [obsidianmd/obsidian-clipper#50]
Hello.

First of all, great work on the extension. It is working very well in a few tests I did.

A small suggestion would be for the extension to also have a context menu, when some text is selected.. 

My muscle memory tends to right click -> Clip when dealing with selections versus going to the extension icon, when I want to clip a full page.

It would also be consistent with other extensions I use,  like Raindrop for annotations or MarkDownload.

The menu could simply open the main extension screen (the same behavior as clicking on the extension icon).

Not a blocker of any kind and I probably can adapt. just a nice to have.

**Comment by kepano** [comment]
Will be in the next update

**Comment by kepano** [comment]
Added to 0.5.0
