### ISSUE TITLE
Nothing is saved when clicking "Add to Obsidian"

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-clipper#51]
Web Clipper requires Obsidian 1.7.2+ to clip long content for most users on Windows or Edge

If you are having trouble clipping a page, make sure you are a [Catalyst member](https://help.obsidian.md/Licenses+and+payment/Catalyst+license), using the latest [Early Access version](https://help.obsidian.md/Obsidian/Early+access+versions) of Obsidian (1.7.2+).

The reason for the issue is that some combinations of browsers and operating systems have a limited URI length. The new version of Obsidian allows passing the page content via the clipboard rather than via URI.

If you want to use the old method go to **Web Clipper Settings** → **General** and turn on **Legacy mode** — but be aware that this has the same limitation, particularly on Windows.

**Comment by BlueNoob** [comment]
> Web Clipper requires Obsidian 1.7.2+ to clip long content for most users on Windows or Edge
> 
> If you are having trouble clipping a page, make sure you are a [Catalyst member](https://help.obsidian.md/Licenses+and+payment/Catalyst+license), using the latest [Early Access version](https://help.obsidian.md/Obsidian/Early+access+versions) of Obsidian (1.7.2+), then go to Web Clipper settings and turn on the toggle for early access features.
> 
> The reason for the issue is that some combinations of browsers and operating systems have a limited URI length. The new version of Obsidian allows passing the page content via the clipboard rather than via URI.

But I can only get v1.6.7 from github and website.

**Comment by kepano** [comment]
You need a Catalyst membership. See link above.

**Comment by kepano** [comment]
Web Clipper 0.7.0 now requires Obsidian 1.7.2 and passes a message to users on older versions.

**Comment by Redster1** [comment]
Howdy, I'm a Catalyst member on v1.7.4 of Obsidian and using Windows and Arc.  Currently, the web clipper will put the article onto my clipboard and will open Obsidian, but that's all that it will do. I then have to create a new note, paste it in and then edit the title.  I hope this is helpful!

**Comment by kepano** [comment]
> Howdy, I'm a Catalyst member on v1.7.4 of Obsidian and using Windows and Arc. Currently, the web clipper will put the article onto my clipboard and will open Obsidian, but that's all that it will do. I then have to create a new note, paste it in and then edit the title. I hope this is helpful!

Can you open the developer console in Obsidian and look at the URI that was received? Perhaps there is an issue with the note title. You can get more help in the clipper channel on Discord.

**Comment by Redster1** [comment]
When I opened the Developer console, I could see that it was because I had typed in the "Web Clips" folder path manually in the web clipper and I had accidentally given a backwards slash "\" when a forwards slash "/" was needed. So, it was loading things into my clipboard, opening up Obsidian, but then failing silently.  Opening the console, I could see that an object was received, but the file path was broken and it gave this error: "Folder Already Exists"
![image](https://github.com/user-attachments/assets/b610e9b1-521d-40c0-90ba-e811a5868bd1)

Thanks!

**Comment by fabioscarsi** [comment]
> clipper channel on Discord

@kepano, I can't find the channel. Can you link it? Thanks

**Comment by kepano** [comment]
> @kepano, I can't find the channel. Can you link it? Thanks

https://discord.com/channels/686053708261228577/1285652864089198672

**Comment by kepano** [comment]
Obsidian 1.7.4 is now available publicly. This should fix the issue for Windows/Edge users.
https://obsidian.md/download
