### ISSUE TITLE
Keep indentation and avoid escaping when clipping code blocks

### ISSUE THREAD

**Issue by brpaz** [obsidianmd/obsidian-clipper#53]
I was experimenting the clipper to clip code blocks to my vault, but it´s not keeping the formatting and indentation. Also, it´s escaping some characters like `>` or `=` in html tags.

For example, clipping this code block: https://docs.astro.build/en/basics/astro-pages/#using-with-a-library results in the following:

```
<html\>

<head\>

<title\>My page</title\>

<script src\="https://unpkg.com/htmx.org@1.9.6"

integrity\="sha384-FhXw7b6AlE/jyjlZH5iHa/tTe9EpJ1Y55RjcgPbjeWMskSxZt1v9qkxLJWNJaGni"

crossorigin\="anonymous"\></script\>

</head\>

</html\>

<section\>

<div id\="parent-div"\>Target here</div\>

<button ==hx-post\="/partials/clicked/"==

hx-trigger\="click"

hx-target\="#parent-div"

hx-swap\="innerHTML"

\>

Click Me!

</button\>

</section\> 
```

Is there any way I can keep it formatted?

I am just using the default `{{content}}` tag. I have looked into filters, but I couldn´t find anything that works for my use case.

Thank you.

**Comment by kepano** [comment]
Fixed in 0.6.0

**Comment by brpaz** [comment]
@kepano I have 0.6.0 and seems to have the same behavior. Tested on both Firefox and Chrome browsers.

Also the right-click menu, is not working on Firefox. The item appears on the context menu, but does nothing on click.

**Comment by kepano** [comment]
I just tested on Firefox and Chrome. Both are working well. It sounds like you need to double check that you have the latest and reload the extension.

**Comment by MelodyDuplaix** [comment]
I have the same problem on desktop with the right-click menu, with the 0.6 version of the extension, nothing happens when I click on the item, whereas otherwise it works very well. But I use Zen Browser (based on Firefox) as browser, maybe it comes from there.

**Comment by kepano** [comment]
Let's keep the discussion focused. See #50
