### ISSUE TITLE
Question: the difference between this plugin and Obsidian's default frontmatter format

### ISSUE THREAD

**Issue by Moyf** [obsidianmd/obsidian-clipper#55]
![image](https://github.com/user-attachments/assets/a9ffd1b2-d834-4162-88e2-01b1b8f92bf6)

It seems that all the properties added by this extension would be `"xxx"` (surrounded by the double quotes)
However, it seems that the 'datatime' doesn't have these quotes?

If I change the datatime in Obsidian, the Frontmatter would change from:
![image](https://github.com/user-attachments/assets/71116755-b9b3-4423-82c5-d292099cfcec)

to:
![image](https://github.com/user-attachments/assets/4fb85e17-f30c-4364-bb24-942c07aea446)

Is there any setting for this quotes format?

**Comment by kepano** [comment]
You're right. When using the date or datetime type in Web Clipper we should not use quotes to match the Obsidian app formatting. This change will be in the next version.

**Comment by kepano** [comment]
Will be fixed in 0.5.1

**Comment by Moyf** [comment]
> Will be fixed in 0.6.0

Could it be possible to not adding double quotes symbol for other properties?

Because when I change the property in "Note property view" (the core plugin), it would automatically remove the quotes anyway:
![e6b4051d-c990-410e-8808-73d7ca314fa1](https://github.com/user-attachments/assets/96ab7f9e-c1be-4704-a60c-14b8033e9feb)

(Tested in the Sandbox vault and it seems that it's the default behavior 🤔)

![image](https://github.com/user-attachments/assets/1911a3f0-a3fc-4e3d-b972-ac085fc4b360)


---

And (v0.6.1) it seems that no matter what format I set, the string of datetime would always be :
![image](https://github.com/user-attachments/assets/34589042-2bf8-4c4b-a129-019e19e9abf6)
![image](https://github.com/user-attachments/assets/1e6a1cef-899b-4933-a3d0-2eb512c11e0b)

The date format is inconsistent with all my other notes (which causes issues with Dataview processing), and I would prefer to have complete control over the format.

**Comment by kepano** [comment]
Well you can set your field as a string type, the it will be passed through as is

**Comment by Moyf** [comment]
> Well you can set your field as a string type, the it will be passed through as is

![image](https://github.com/user-attachments/assets/33e169f7-f9a3-4a8a-be28-523e665edb1e)
Then the issue of "double quotes" would arise again.  😂

**Comment by Moyf** [comment]
> > Well you can set your field as a string type, the it will be passed through as is
> 
> ![image](https://private-user-images.githubusercontent.com/4013062/369767048-33e169f7-f9a3-4a8a-be28-523e665edb1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzI2MzEsIm5iZiI6MTcyNzA3MjMzMSwicGF0aCI6Ii80MDEzMDYyLzM2OTc2NzA0OC0zM2UxNjlmNy1mOWEzLTRhOGEtYmUyOC01MjNlNjY1ZWRiMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDYxODUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNiM2E0NTM5OTlkYTNjN2RmYmVmNGQyYWQ4OTZkYmM1ZWY2MDkzNzM4OTBlZDM5NmNiM2ZjNTUyZGQ0MGM1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Hp2y5aZid5DR_Yux4Sz0_0HW2LubJrpBBK1Sf6E8u1g) Then the issue of "double quotes" would arise again. 😂

![image](https://github.com/user-attachments/assets/db85d6d2-1c56-49ff-a37a-870718986607)
I set the type to `Text`, is it correct?

( How can I get rid of double quotes ?

**Comment by kepano** [comment]
Okay I see the issue. This will be fixed in the next version you will be able to use `date` and `datetime` types with custom date formats.

**Comment by Moyf** [comment]
> Okay I see the issue. This will be fixed in the next version you will be able to use `date` and `datetime` types with custom date formats.

Great! Thank you!

In addition, I would like to understand whether wrapping text property in double quotes is a Markdown syntax rule for YAML? I am a bit confused as to why Obsidian natively removes these double quotes.

**Comment by ar-rm** [comment]
This continues to be an issue with `text` strings (not `date` or `datetime`).

It is exactly as @Moyf describes and shows in screenshots/videos.

Specifically: https://github.com/obsidianmd/obsidian-clipper/issues/55#issuecomment-2367173175

Obsidian removes the double quotes when *it* parses the file after modifying a property.

> In addition, I would like to understand whether wrapping text property in double quotes is a Markdown syntax rule for YAML? I am a bit confused as to why Obsidian natively removes these double quotes.

Agreed.

Maybe this has something to do with it?:
https://forum.obsidian.md/t/yaml-properties-api-processfrontmatter-removes-string-quotes-comments-types-formatting/65851/6
