### ISSUE TITLE
Notes creating incorrectly

### ISSUE THREAD

**Issue by probablySophie** [obsidianmd/obsidian-clipper#56]
I'm using:  
* Linux (OpenSUSE Leap)
* Firefox (Flatpak)  
* Obsidian 1.6.7
* The firefox store version of the extension

Using the extension on my phone I have no issues, however, using the desktop version the notes aren't creating properly.

I'm trying to create `_Meta/Web Clippings/Article Title.md` and I get `_Meta/Web.md`, with no content.  
Changing it to `Web-Clippings` makes a new empty note: `_Meta/Web-Clippings/Article.md`

I checked the console, and it looks like the app is receiving:
![image](https://github.com/user-attachments/assets/7685c6d1-1e93-42c1-91e6-974b695af3cc)

So something is either going wrong in the URL construction, or the handover?  I'll have a poke around when I have time to see if I can figure out what's going on.

Edit: _Maybe just ignore me for the moment?? I've just tried it on OpenSUSE Tumbleweed, and it works perfectly.  So there's a chance that its something funky about Leap_ 🙃

**Comment by kepano** [comment]
Issues should only be opened if you're using Obsidian 1.7.2+

**Comment by kepano** [comment]
Please use the new bug creation template if you still experience this issue on Obsidian 1.7.2+
