### ISSUE TITLE
T letter in date/time type filter

### ISSUE THREAD

**Issue by hmnijp** [obsidianmd/obsidian-clipper#60]
I'm trying to get the "date/time" type properties of the format `YYYY-MM-DDTHH:mm`,
but all filter options ignore the letter T, I suspect the filter breaks when using it:

`{{schema:uploadDate|date:"YYYY-MM-DDTHH:mm"}}` => `2024-09-19 18:30:00`  
(ss=00 is added, I think this is the default template when an error occurs.)

`{{schema:uploadDate|date:"YYYY-MM-DD-HH:mm"}}` => `2024-09-19-18:30`

`{{schema:uploadDate|date:"YYYY-MM-DD'T'HH:mm"}} `=> `2024-09-19'T'18:30`

The only way I've gotten it to work is to use the “text” properties type and specific template, but it adds quotation marks `" "` :
`{{time|date:"YYYY-MM-DD"}}T{{time|date:"HH:mm"}}` => `"2024-09-19T18:30"`

The source string is `schema:uploadDate` from the youtube-clipper.json template:
`2024-09-19T07:30:24-07:00`

**Comment by kepano** [comment]
This will be fixed in the next update. The issue was that time type properties were being converted to `YYYY-MM-DD HH:mm:ss`, now they will always use `'YYYY-MM-DDTHH:mm:ssZ` to adhere to the YAML standard. If you want a different format you may need to change the property type to `text`.
