### ISSUE TITLE
math support

### ISSUE THREAD

**Issue by KraXen72** [obsidianmd/obsidian-clipper#63]
First of all, thank you for finally making an official clipper extension! So glad it's open source!
I suggest the following:
support these math formats and turn them into mathjax codeblocks.

- [ ] mathjax v2 (most websites using mathjax use this, only examples i have are login-gated)
- [ ] mathjax v3: test pages:
https://mathjax.github.io/MathJax-demos-web/tex-chtml.html
you might have to extract it from the global mathjax object, [something like this](https://github.com/KraXen72/yoink/blob/main/entrypoints/page.ts)

- [ ] katex:
https://katex.org
https://sixthform.info/katex/examples/centraliser.html
on some pages it's easy to extract, on some  not.

i think i implemented it for my web clipper (unfinished) half a year ago: https://github.com/KraXen72/yoink
feel free to take a look at how i implemented it if it helps and if it even works now.
currently unable to port it for obsidian-clipper and PR due to lack of time

**Comment by kepano** [comment]
Please do some testing with the latest version of before opening requests. All of these cases are already supported :)

**Comment by KraXen72** [comment]
ah, sorry. i was just testing it with the version on chrome store. thanks!

**Comment by kepano** [comment]
I works with the version on the Chrome storeOn Sep 24, 2024, at 01:29, KraXen72 ***@***.***> wrote:﻿
ah, sorry. i was just testing it with the version on chrome store. thanks!

**Comment by KraXen72** [comment]
when using clipper on this site, the math is not extracted
https://interactivetextbooks.tudelft.nl/delftse-foundations-of-computation/content/sets/relations.html
