### ISSUE TITLE
implement framework for site-specific fixes

### ISSUE THREAD

**Issue by KraXen72** [obsidianmd/obsidian-clipper#64]
**Describe the solution you'd like**
mozilla's readability is great, but it has a lot of issues where it's heurestics cause it to miss some paragraphs of text.
for example, [here](https://www.theverge.com/2022/10/28/23428132/elon-musk-twitter-acquisition-problems-speech-moderation), the first paragraph isn't extracted

i've opened an issue on their repo a long time ago and it wasn't fixed. by the looks of it, they get a lot of similar issues.
i suggest creating an framework internally in the extension to accomodate site specific fixes:

[this is how i did it for my web clipper](https://github.com/KraXen72/yoink/blob/main/lib/process-html.ts#L38), specifically the HTMLRewriter class, which is simple in nature but allows easy specifying of site-specific fixes.
feel free to use a similar approach, or a completely different one, if necessary.

another option could be forking the readability extension, but that just increases maintainance burden

**Comment by kepano** [comment]
There is already support to bypass readability in templates using `{{fullHtml}}` and `{{selectorHtml}}` so this doesn't seem necessary. In the long-term maybe we would change the `{{content}}` variable to something more clever and remove Readability altogether.
