### ISSUE TITLE
use joplin's turndown fork

### ISSUE THREAD

**Issue by KraXen72** [obsidianmd/obsidian-clipper#65]
joplin is an another markdown note-taking app which maintains it's own improved version of turndown.
see: https://github.com/laurent22/joplin/tree/dev/packages/turndown

feel free to stay on upstream turndown, but it might be worth considering switching to this.

**Comment by kepano** [comment]
We have our own set of rules that are more specific to Obsidian so it doesn't seem necessary to me.
