### ISSUE TITLE
A way to clip reddit or more specificly new sub-reddit topics, contents and comments for the last 24 hours to use as a readitlater and saving it as daily notes in daily folders

### ISSUE THREAD

**Issue by yellowbikewithbluehandles** [obsidianmd/obsidian-clipper#70]
Sorry about being hyper specific haha, but this is what I have been trying to get web clippers to do but have been failing. I have gotten it to work for titles and topics through rss and the same with comments with rss but not together because apparently in reddit rss the topics and comments are separate and thus its a jumbled mess. And using the other templates it clutters the notes with random icons or double or even triple posts the same things and I have even tried using markdownloader but that also fails to bring the reddit clippings into obsidian as markdown because it loses the comments or loses the markdown contents or even just plainly not downloading let alone only 10% of the time downloading anything like images if it has that, it is widely inconsistent.

Even just being able to web clip a reddit topic correctly with all its contents and comments as markdown or any other format cleanly would be awesome.
I would like to see what happened that day and write notes about it which is what I have so badly been wanting to set up. It would be nice to automatically have all the articles videos and images and daily happenings for that day from reddit just go into a folder every 24 hours or when I press a button to write about or just have as a way to look back and write notes on it like a diary and without distractions be able to keep up with what I am interested in.

Once again sorry about being so hyper specific I just don't want to miss my opportunity to ask for something! Thank you very much for reading and thank you so much for obsidian and all you do!

**Comment by esodesod** [comment]
Not directly related to the obsidian-clipper, but I guess "reddit-markdown" (https://github.com/chauduyphanvu/reddit-markdown) should solve your needs (if I understand your description). Personally, I only use it for one-off posts/items (via a container/docker), but you can set it up to run automatically, fetch all new posts (into Markdown), etc.; nicely ready for review/annotations in Obsidian later, if that's your taste.

**Comment by kepano** [comment]
This is possible if you create a template using the right combination of variables and filters. Discussions about templates for specific sites should be in the obsidian-clipper channel on the official [Obsidian Discord](https://obsidian.md/community). This repo should be used for bug reports and feature requests, not discussions.
