### ISSUE TITLE
BUG: Safari Extension Causes Display Issues on Websites (YouTube, GitHub)

### ISSUE THREAD

**Issue by voi-tech** [obsidianmd/obsidian-clipper#71]
**Version (please complete the following information):**
 - OS: MacOS Sequoia
 - Browser: Safari
 - Web Clipper version: 0.8.0
- Obsidian version: 1.7.3

**Describe the bug**
When the Obsidian Web Clipper extension is enabled in Safari, certain websites such as YouTube and GitHub do not display correctly. Layouts and elements are misaligned or not rendered properly, making the pages difficult to navigate.

**To reproduce**
	1.	Install the Obsidian Web Clipper extension from the Mac App Store.
	2.	Enable the extension in Safari.
	3.	Open YouTube or GitHub.
	4.	Observe the visual issues with page layout and functionality.

**Expected behavior**
Websites like YouTube and GitHub should display properly without any layout issues or visual errors when the extension is enabled.

**Your template file**
[default-clipper.json](https://github.com/user-attachments/files/17176158/default-clipper.json)

<img width="1442" alt="SCR-20240928-tabx" src="https://github.com/user-attachments/assets/60be09d6-c053-4425-b8f8-4be44da9f8d4">
<img width="1442" alt="SCR-20240928-tafg" src="https://github.com/user-attachments/assets/87057e21-3dfe-4ba5-8605-1fc74d049048">

**Comment by kepano** [comment]
This is already fixed in 0.8.1 but it hasn't been approved by Apple yet.
