### ISSUE TITLE
Use a clickable checkbox for properties type "checkbox" in the template selection menu.

### ISSUE THREAD

**Issue by hmnijp** [obsidianmd/obsidian-clipper#75]
To change the state of the checkbox, you have to delete "false" and type "true" - it would be more convenient to do it with a single mouse click, like in Obsidian itself... )

![2024-10-02 01-20-09](https://github.com/user-attachments/assets/8a5c6723-7fc1-49ef-8a06-7b0fc891d3b6)

**Comment by kepano** [comment]
I agree, will add soon
