### ISSUE TITLE
The size of the popup window is not enough when the scale is >100%.

### ISSUE THREAD

**Issue by hmnijp** [obsidianmd/obsidian-clipper#76]
When using zoom in the browser settings (chrome/edge - chrome://settings/appearance -> page zoom) the size of the popup is a bit smaller than I would like:
the "add to obsidian"/"template selector" button is hidden and I have to scroll to click it. 
You could slightly increase the size of the window depending on the zoom to get rid of the scrollbar...
![2024-10-02 01-35-18](https://github.com/user-attachments/assets/fd5412ec-b0c6-461f-ae4f-3e55d5a24e2f)

**Comment by kepano** [comment]
Ok, I think I found a solution. Should be in 0.8.4
