### ISSUE TITLE
BUG: Clipper version stuck at 0.7.2 in the official Firefox Add-on Store

### ISSUE THREAD

**Issue by amperag** [obsidianmd/obsidian-clipper#77]
**Version (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Web Clipper version: 0.7.2
 - Obsidian version: Not relevant

**Describe the bug**
It seems to me that since release 0.7.2, the version for Obsidian Web Clipper is stuck. So at least for Firefox, every new release since 0.7.2 is missing. It says 0.7.2 in the official store and in my Firefox extensions settings.

**To reproduce**
1. Go to the official [Firefox Add-on store](https://addons.mozilla.org/de/firefox/addon/web-clipper-obsidian/).
2. Scroll down to "Further Information".
3. See that "Version" is stuck at 0.7.2
4. See that "Last Updated" states "7 Days" (at least for me)

**Expected behavior**
The newest release of the Obsidian web clipper should be available for Firefox.
As of today that would be 0.8.3.

**Your template file**
Not relevant.

---

Picture from Firefox Add-on store:

![grafik](https://github.com/user-attachments/assets/ce8c3d38-d8ca-4e16-a2b3-da3dd8f86efa)

Picture from the extensions overview in my Firefox browser:

![grafik](https://github.com/user-attachments/assets/247e6535-e580-4945-b50f-6361bd0f799b)

**Comment by kepano** [comment]
It's not a bug. All the versions have been submitted but the Firefox team has not approved them yet. I'm not sure why. Review time has been slower for the last few days.
