### ISSUE TITLE
Allowing `map` or `template` filter to work with string literal

### ISSUE THREAD

**Issue by 9diov** [obsidianmd/obsidian-clipper#81]
My use case is to add a prefix to a list of values, for example I want to extract Genres from a Goodreads page, and turn that into a list of Wikilink like this: ["genres/Nonfiction", "genres/Fitness"]. I thought that it is possible to do this with `map` and `template` filters but it turned out they only work with object-based items, not strings. 

**Describe the solution you'd like**
There are 2 ways transforming list of strings like above can be done:
* Allowing `map` to convert a string to an object then use `template` e.g. `map:item => {str: item}|template:"genres/${str}"` 
* A keyword such as `_item` to refer to the original item e.g. `template:"genres/${_item}`

**Comment by kepano** [comment]
Should be improved in 0.9.3 but some more work is needed. See readme.

**Comment by kepano** [comment]
@9diov can this issue be closed, as far as your use case is concerned?

**Comment by 9diov** [comment]
@kepano Sure. Thanks a lot for your work.

**Comment by soumitradev** [comment]
I spent an hour bashing my head against this thing, but I found this issue and finally figured out what I wanted to do!

I wanted a way to keep track of news publishers, authors etc. to keep track of how trustworthy or biased each site/author is, and this issue gave me just what I wanted.

Just as an additional example, I wanted wikilinks for each author/publisher on the clipped page so I can quickly set up pages for them, and this worked:
`{{author|split:", "|map:item => "[[05 - Resources/99 - Sources/${item}|${item}]]"|template: "${str}, "|join}}`

The important part is the `"${str}, "` part in the template. I tried all kinds of versions of `"${str} "` and `"${str}\n"` but none of that seemed to work. Adding the comma there was the only thing that would separate the wikilinks.

Huge props to the obsidian team for this tool! 🙌

**Comment by kepano** [comment]
For reference the information can be found here:
https://help.obsidian.md/web-clipper/filters#%60template%60
