### ISSUE TITLE
BUG: faild to link to clippings from other documents.

### ISSUE THREAD

**Issue by rainyear** [obsidianmd/obsidian-clipper#82]
**Version (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Web Clipper version: 0.8.4
- Obsidian version: v1.6.7

**Describe the bug**
When creating a link to a clipping from another document, the clipping document can be retrieved, but the created link cannot open and instead a new document is created.

**Comment by kepano** [comment]
What is the name of the clipped file? What is the link text?

**Comment by rainyear** [comment]
After turning on the option for automatic update of internal links, the problem is solved!

<img width="760" alt="image" src="https://github.com/user-attachments/assets/ce5a49f7-4422-487e-9ce9-09d9f3c73ae3">
