### ISSUE TITLE
Extensibility Request: Integration of Third-Party Scripts in Obsidian Web Clipper

### ISSUE THREAD

**Issue by LeonelRFF** [obsidianmd/obsidian-clipper#86]
Hello, I want to contribute an idea, is it possible that within this plugin you can download scripts that plugin developers can create to explore more possibilities?
Let me explain, although I am not a programmer, suppose that the developer of plugin A, creates a function which can be downloaded from the configuration of Obsidian Web Clipper, which allows the content to be processed, grouped, classified, etc, I can not imagine the possibilities because they must be as many as creativity. 
Greetings.

**Comment by fabioscarsi** [comment]
Great point @LeonelRFF. 
It would be great to enable some pre-processing in Obsidian Web Clibber with LLMs before saving to Obsidian. Considering that the clipper gets the text and all available metadata from the page, it would be feasible to pass this data to an LLM to generate for example a summary, tags, ... 
I'm not a coder, but, for example, danielmiessler/fabric gives many good prompts that could be applied to the text and the page metadata to automate and greatly improve the collecting process. 
@kepano , do you think it could be done starting from your code? Is it an interesting and practical idea? 
For sure, if feasible, it would be a really innovative idea capable of enabling fantastic new workflows .....

**Comment by kepano** [comment]
@fabioscarsi prompt variables are already supported, but not yet documented. You need to enable the feature by going to `settings.html?section=interpreter`

**Comment by fabioscarsi** [comment]
WOW!

**Comment by veeragoni** [comment]
it seems like we OpenAI key is mandatory and its not working with 3P models with OpenAI compatible API provider
<img width="1142" alt="Screenshot 2024-10-17 at 3 38 39 PM" src="https://github.com/user-attachments/assets/cf4016cc-64ff-4448-9a7f-ae6e20561934">
<img width="1222" alt="Screenshot 2024-10-17 at 3 38 59 PM" src="https://github.com/user-attachments/assets/b8e60941-dfb9-4b5f-bd95-d25279a1f5ad">

**Comment by kepano** [comment]
The feature is not complete that's why it is not enabled yet.

**Comment by fabioscarsi** [comment]
@kepano, can we help you and start at least with some beta testing? Or is it too early? This feature seems to have really impressive potential ....

**Comment by laughedelic** [comment]
This works great with an OpenAI API key 👏 Thank you for sharing this beta feature 🫶

**Comment by yousecjoe** [comment]
It works great with an OpenAI key but fails when using my local Ollama, saying it needs an OpenAI key.

**Comment by kepano** [comment]
I'm closing this since we've strayed off topic and the Interpreter feature is not yet live.
