### ISSUE TITLE
Copy to clipboard behavior

### ISSUE THREAD

**Issue by reply2za** [obsidianmd/obsidian-clipper#87]
Can Clipper have a "Copy to clipboard" behavior. This would be useful for inserting into the random notes that I happen to working on at any given time.  

I know I can "ctrl+A" and then "ctrl+C" on the preview but pressing the button at the bottom instead would surely save a step every time.

**Comment by kepano** [comment]
Can you clarify what the use case is? Have you considered using "Add to existing note" in your template?

**Comment by reply2za** [comment]
I like to have certain notes open in Obsidian, and while doing research, place a reference to the site (in a certain format) in the note. The thing is that there isn't any one note that I would put the reference in, so creating an "add to existing note" for every note in my vault would be overkill.

**Comment by kepano** [comment]
This was added in 0.9.7
