### ISSUE TITLE
Why not support for Edge

### ISSUE THREAD

**Issue by EthantLu** [obsidianmd/obsidian-clipper#88]
Why not support for Edge

**Comment by kepano** [comment]
Edge is already supported, but it essentially requires Obsidian 1.7 which is in early access. In the meantime you can install the Chrome extension on Edge, see readme. Once Obsidian 1.7 is available publicly, we will add it to the Edge adding store.

**Comment by kepano** [comment]
Web Clipper is now on the Edge store:
https://microsoftedge.microsoft.com/addons/detail/obsidian-web-clipper/eigdjhmgnaaeaonimdklocfekkaanfme
