### ISSUE TITLE
BUG: Cant change Template

### ISSUE THREAD

**Issue by ryan-royals** [obsidianmd/obsidian-clipper#94]
**Version (please complete the following information):**
 - OS: Windows
 - Browser Arc browser
 - Web Clipper version: 0.9.3
- Obsidian version: 1.7.4

**Describe the bug**
Cant change the template. Clicking on `Default` in the side menu does nothing

**To reproduce**
1. Open Side Menu
2. Attempt to change the template

**Expected behavior**
Drop down should appear showing all your templates.

**Comment by kepano** [comment]
This is a known bug with Arc browser on Windows. Select elements are hidden behind the extension pane. Please report directly to the Arc team.

**Comment by ryan-royals** [comment]
> This is a known bug with Arc browser on Windows. Select elements are hidden behind the extension pane. Please report directly to the Arc team.

Excellent, thanks for letting me know.
